areas_ctf = (['RPG: Mago de Etheria®',
              'RPG: Caçador de Rauberior®',
              'RPG: Sábio de Ilumiora®',
              'RPG: Ceifador de Kerontaris®',
              'RPG: Sacerdote de Widebor®',
              'RPG: Ranger de Jangalor®',
              'RPG: Paladino de Yotungar®',
              'RPG: Samurai de Shoguriar®',
              'RPG: Domador de Dracaris®',
              'RPG: Guerreiro de Forgerion®'])

perg_pq = (
    ['porque',
     'por que',
     'porquê',
     'por quê'])

perg_qual = ([
    'quando',
    'como',
    'onde',
    'qual',
    'quanto',
    'quem'])

denky_f = ([
    'Você quer mesmo que eu fale mal do meu criador?',
    'Eu não vou cair nesse tipo de armadilha!',
    'Você acha que eu sou algum tipo de otária?',
    'Eu não sou autorizada a dar minha opnião quando se trata do meu criador!'])

denky_r = (
    ['feio',
     'gordo',
     'noob',
     'gay',
     'viado',
     'capitalista',
     'corrupto',
     'mentiroso'])

resposta_comum = (
    ['Não respondo a isso!',
     'Sim!',
     'As vezes!',
     'Não!',
     'Claro!',
     'NUNCA!',
     'Um dia talvez!',
     'A resposta está dentro de ti!',
     'Mais ou menos!',
     'Certamente que sim!',
     'Tenho minhas dúvidas...',
     'Se você diz...',
     'Não seria ao contrário?',
     'Fico imaginando isso...',
     'Nesse ponto, ate você!',
     'Tenho quase certeza!',
     'Sempre que pode!',
     'Como você sabe disso?'])

resposta_ou = (
    ['A primeira opção',
     'A ultima opção',
     'A Segunda opção',
     'Estou indecisa!',
     'Qualquer uma das opções',
     'Faço a mínima ideia',
     'Eu escolher não vai fazer diferença!',
     'O que vc escolheria? Eu acho o mesmo que você!',
     'A primeira opção pra mim e outra pra voce!',
     'Tudo!',
     'Nem um nem outro...',
     'Qualquer coisa é a mesma coisa!'])

resposta_pq = ([
    'porque sim!',
    'porque não!',
    'porque sempre será assim!',
    'porque não há nada que nós possamos fazer!',
    'porque você me pergunta isso?'])

resposta_outras = (
    ['Não gosto desse tipo de pergunta!',
     'Me faça outro tipo de pergunta...',
     'Você acha que eu sou a Cortana ou a Siri para responder sobre isso?',
     'Vai procurar o google, mané!'])

bomdia = (['Enquanto você dormia, Deus preparou um lindo dia para você. Bom Dia!',
           'Desacelere. A vida merece atenção. Se tiver pressa, que seja de ser feliz. Bom dia!',
           'Cuide, cultive, queira o bem. O resto vem. Bom dia!',
           'Bom dia! Não demore muito para perceber que é preciso pouco para ser feliz.',
           'Espero que a sua manhã seja tão contagiante quanto o seu sorriso. Tenha um bom dia!',
           'Bom dia! Que cada segundo do seu dia seja guiado pelas mão de Deus e que você tenha um dia maravilhoso '
           'ao lado '
           'das pessoas que você ama.',
           'Bom dia! A vida é um milhão de novos começos movidos pelo desafio sempre novo de viver . Aproveite esse '
           'dia para '
           'desfrutar das coisas boas que fazem você feliz.',
           'Faça do bom humor seu aliado e você sempre acordará com o pé direito. Bom dia!',
           'Se queremos progredir, não devemos repetir a história, mas fazer uma história nova. (Mahatma Gandhi)',
           'Hoje seu dia será especial. Muito melhor que ontem e um aprendizado para amanhã. Hoje você tem a '
           'oportunidade de '
           'fazer as coisas diferentes. Tenha um ótimo dia!',
           'A vida tem 4 sentidos: amar, sofrer, lutar e vencer. Portanto ame muito, sofra pouco, lute bastante '
           'e vença '
           'sempre. Bom dia!',
           'Como é bom começar o dia pensando em você. Tenha um excelente dia!',
           'O ontem já passou, o amanhã é um mistério, o hoje é uma benção. Tenha um bom dia!',
           'Hoje acordei e a primeira coisa que me veio a cabeça foi você. Isso só pode ser um bom sinal. Te desejo um '
           'ótimo dia.',
           'Bom dia! Hoje é o dia da conquista, da superação, de dar a volta por cima. Tenha fé!',
           'Bom dia! Lembre-se que hoje você tem a chance de fazer diferente. O seu sucesso e a sua felicidade '
           'dependem das '
           'suas escolhas.',
           'Ninguém pode voltar no tempo e fazer um novo começo, mas podemos começar agora a fazer um novo fim. Um dia '
           'iluminado pra você!',
           'Bom Dia. Que a cada manhã, você sinta em seu coração a certeza de que a vida lhe espera de braços abertos, '
           'para receber suas expectativas e realizá-las uma a uma.',
           'Bom dia! Hoje eu desejo pra você aquilo que eu tenho certeza que você deseja pra mim: Um dia abençoado.',
           'Hoje certamente tudo dará certo. O seu caminho será suavizado pela brisa do ar que chegará até você '
           'de mansinho, '
           'trazendo com ela o aroma das flores que darão colorido ao seu dia.',
           'Quero que você comece o seu dia sentindo todo o meu amor e meu carinho. Te amo!',
           'Mesmo caminhando entre espinhos e com muitas pedras nos caminhos continue caminhando com coragem e '
           'confie no '
           'poder Daquele que é maior. Tenha um maravilhoso dia!',
           'A angústia de ter perdido não supera a alegria de se ter um novo dia para tentar de novo. Um bom dia '
           'pra você!',
           'Bom Dia é a palavra mágica que faltava nesta manhã, e vem expressar à você o maravilhoso amanhecer que lhe '
           'desejo, repleto de amor e paz.'
           'Lembre-se sempre: Cada dia nasce de um novo amanhecer. Tenha um ótimo dia.',
           'Sorria, desejo à você um excelente dia. Muita paz, muita alegria e um dia super feliz!'])

boanoite = (
    ['Apague as luzes, esqueça os problemas, descanse o corpo e deixe a alma livre para sonhar. Boa noite!',
     'A noite é uma boa oportunidade para descansar, perdoar, esquecer, sonhar e se preparar para as lutas do dia '
     'seguinte. Pense nisso. Boa noite!',
     'Talvez seja você. A vida vai dizer. De qualquer forma, obrigado por me fazer dormir sorrindo.',
     'Não perca a esperança. Você nunca sabe o que o amanhã irá trazer. Boa noite e bons sonhos!',
     'Deixe os sonhos tomarem conta de você. Os sonhos são necessários à vida. Que os anjos embalem seu sono ! E jogue '
     'fora tudo de ruim do dia que passou.',
     'Como é bom ir dormir pensando em quem se ama. Boa noite. Durma com os anjos!',
     'Quando a noite chegar você já sabe que vou estar sempre pronto para te dar um beijo de boa noite.',
     'Durma com os anjos e sonhe comigo ... mas se preferir durma comigo e sonhe com os anjos.',
     'A experiência traz sabedoria. Que as lições aprendidas com mais esse dia de vida embalem seu sono. Boa Noite.',
     'Espero que você tenha uma ótima noite! Aproveite e sonhe com os anjos.',
     'Quando esta noite uma leve brisa tocar teu corpo, não se assuste ... é a minha saudade que vai beijar em '
     'silêncio o teu corpo. Boa noite.',
     'Quem de manhã compreendeu os ensinamentos da sabedoria à noite pode dormir o sono dos justos. Boa noite.',
     'Quem respeita a vida merece uma ótima noite de sono. Durma bem!',
     'Nada como uma boa noite de sono para repor as energias. Tenha uma boa noite!',
     'A noite acendeu as estrelas porque tinha medo da própria escuridão. Boa noite.',
     'O choro pode durar uma noite, mas a alegria vem pela manhã. Te desejo uma boa noite.'])

palin = (
    ['Roma me tem amor.',
     'Socorram-me, subi no ônibus em Marrocos!',
     'A mala nada na lama.',
     'A grama é amarga.',
     'A Rita, sobre vovô, verbos atira.',
     'Olé! Maracujá, caju, caramelo!',
     'Rir, o breve verbo rir.',
     'Anotaram a data da maratona.',
     'A mãe te ama.',
     'Oto come mocotó.',
     'A torre da derrota.',
     'Ótimo, só eu, que os omito.',
     'O galo ama o lago.',
     'O lobo ama o bolo.',
     'Mega bobagem.',
     'A cara rajada da jararaca.',
     'Amar dá drama.',
     'A sacada da casa.',
     'Após a sopa.',
     'Luz azul.',
     'Ame o poema.',
     'A dama admirou o rim da amada.',
     'A diva em Argel alegra-me a vida.',
     'O caso da droga da gorda do saco.',
     'Zé de Lima, Rua Laura, Mil e Dez',
     'Saíram o tio e oito marias.',
     'Assim a aia ia a missa.',
     'Adias a data da saída.',
     'Acuda cadela da Leda caduca.',
     'Aí, Lima falou: Olá, família.',
     'A pateta ama até tapa.',
     'E até o Papa poeta é.',
     'Laço bacana para panaca boçal.',
     'A gorda ama a droga.',
     'Lava esse aval.',
     'Soluço-me sem óculos.',
     'Missa é assim.',
     'Nos ligou o Gilson!',
     'Até time demite, tá?',
     'Irene ri.',
     'Olá, galo!',
     'Ai, Bia!',
     'Ali, lado da Lila.',
     'Amor a Roma.',
     'Até o poeta.',
     'Ladra pardal.',
     'Livre do poder vil.',
     'O céu sueco.',
     'Ser belo: lebres.',
     'Lá vou eu em meu eu oval.',
     'Eco: vejo hoje você.',
     'O muro: rever o rumo.',
     'Orava o avaro.',
     'A Daniela ama a lei? Nada!',
     'A droga do dote é todo da gorda.',
     'A lupa pula.',
     'A miss é péssima!',
     'À Rita, sátira!',
     'Acata o danado... e o danado ataca!',
     'Ajudem Edu já!',
     'A base do teto desaba.',
     'Eva, asse essa ave!',
     'Marujos só juram.',
     'O mito é ótimo.',
     'O trote torto.',
     'O treco certo.',
     'O trote torto.',
     'O voo do ovo.',
     'Ódio do doido!',
     'Oh nossas luvas avulsas, sonho...',
     'Oi, rato otário!',
     'A rua Laura.',
     'Ato idiota.',
     'Arara rara.',
     'O teu dueto.',
     'A babá baba.',
     'Pivete vip!',
     'O Atari piratão.',
     'Rosa esse corpo, processe a dor!',
     'Seco de raiva, coloco no colo caviar e doces.',
     'Amo Omã. Se Roma me tem amores, amo Omã!',
     'Me vê se a panela da moça é de aço, Madalena Paes, e vem.',
     'Luza Rocelina, a namorada do Manuel, leu na moda da Romana: anil é cor azul.',
     'O duplo pó do trote torpe de potro meu que morto pede protetor todo polpudo.',
     'O romano acata amores a damas amadas e Roma ataca o namoro.'])

pensador = (
    ['Transar é arte, gozar faz parte, engravidar é moda. Mas assumir é foda.',
     'Mais vale dois pintos na mão do que um na bunda.',
     'As más-línguas falam de mim, as boas me chupam…',
     'Resisto a tudo, menos a uma tentação.',
     'Você disse que me amava, foi tão gentil, olhei para o calendário e era 1º de Abril.',
     'Um dia foi meu, hoje é seu e amanhã de outra….',
     'Viver é como andar de bicicleta, só manter o equilíbrio que você não cai.',
     'Se você sorri, eu dou risada com você, se você chora, eu choro com você, se você se joga de baixo de um ônibus '
     'vou sentir sua falta.',
     'Não pisa que eu te esmago, sou pequeno mas causo estrago.',
     'Só tenho o que mereço… humildade veio de berço.',
     'Os velhos costumam dar conselhos porque já perderam a capacidade de dar maus exemplos.',
     'Você é o ar que eu respiro, o calor que me aquece é a medida exata do que me enlouquece.',
     'Me chama de Coca-Cola que eu te mostro o lado bom da vida.',
     'Não sou avião mas todos viajam em mim.',
     'Um dia li que fumar fazia mal, parei de fumar, no outro dia li que beber fazia mal, parei de beber, e outro dia,'
     ' li que fazer sexo fazia mal, parei de ler.',
     'Quem dá aos pobres ainda tem que pagar o motel.',
     'O dia que conheci você, eu caí a seus pés, não por amor ou amizade, mas porque eu escorreguei.',
     'Por maior que seja o buraco em que você se encontra, pense que por enquanto, ainda não há terra em cima',
     'Nada é impossível, apenas teoricamente improvável.',
     'Depois da tempestade, vem a gripe.',
     'Se a vida fosse fácil, bebê não nascia chorando.',
     'Beijo é igual cigarro, não sustenta mas vicia!',
     'Amor é igual pirulito, começa no doce e termina no palito.',
     'Mulher grávida vive reclamando de barriga cheia.',
     'Ser homossexual não é doença, pois doença tem cura…',
     'Depois dos 40 anos, a única coisa que o médico deixa um homem comer com gordura, é sua própria mulher!',
     'Mulher não vale nada, até pobre tem!',
     'Se ferradura desse sorte, burro não puxava carroça!',
     'Não roube! O Governo não gosta de concorrência.',
     'O amor é cego, mas o matrimônio devolve a visão.',
     'Os seios são iguais a um trenzinho elétrico; é feito para as crianças, mas quem brinca são os adultos.',
     'A mulher mais feliz do mundo é a namorada do saci, pois ela sabe que se levar um pé na bunda, quem cai é ele.',
     'Os políticos são como as fraldas. Devem ser trocados constantemente. E sempre pelo mesmo motivo.',
     'Mulher feia é que nem muro alto, primeiro dá um medo, mas depois a gente acaba trepando.',
     'Homem é como vassoura: sem o pau não serve pra nada.',
     'Não confundir Capitão de fragata com cafetão de gravata.',
     'Conversa entre dois tobogans: Como os anus passam depressa.',
     'Mulher de amigo meu é que nem violino: Eu viro a cara e meto a vara!',
     'Coração de mulher é igual circo, sempre tem lugar pra mais um palhaço.',
     'O povo diz quem tem boca vai a Roma, pois o fogão lá da minha casa tem seis bocas e nunca saiu da cozinha.',
     'Está constatado na Bíblia. O homem mais feliz do mundo foi Adão, porque foi o único que não possuiu sogra.',
     'Homem deve ser tratado como um bom vinho: no escuro, na horizontal, e com rolha na boca.',
     'Homem é igual a orelhão: 80% não funciona e o resto está ocupado.',
     'Só dou carona a quem me dá.',
     'De nada adianta ter barriga de tanquinho se a torneira não funciona.',
     'Amigo é igual parafuso: a gente só vê se é bom na hora do aperto.',
     'O casamento é o método mais caro de se ter uma mulher de graça.',
     'Eu bebo para dormir e acordo para beber.',
     'Mais vale chegar atrasado neste mundo do que adiantado no outro…',
     'Você nasce sem pedir e morre sem querer. Aproveite o intervalo!',
     'Numa coisa homens e mulheres concordam: ambos não confiam em mulheres.',
     'Se o pássaro João-de-barro cagasse barro, meu pai fazia tijolo.',
     'Fiado é igual a barba, se não cortar só cresce.',
     'Mulher de amigo meu é que nem cebola: Eu como chorando.',
     'Eu não quero um príncipe, eu quero um homem que seja capaz de cativar meu coração sem eu ter que me esforçar '
     'pra gostar dele.',
     'Você não foi o homem que eu pedi a Deus, mas foi o melhor que ele me deu.',
     'Só existem dois tipos de mulheres, as que me amam e as que ainda não me conhecem.',
     'Eu queria morrer igual ao meu avô, dormindo bem tranquilo… e não gritando desesperadamente, como os 40 '
     'passageiros do ônibus que ele dirigia.',
     'Se alguém lhe jogar uma pedra, mostre que você é diferente, jogue um tijolo!',
     'Um amigo de verdade não é aquele que separa uma briga, mas sim, aquele que já chega dando voadora.',
     'Promoção: Peça Fiado e ganhe um NÃO!!!',
     'Se for dirigir não beba, se for beber me chame!!!',
     '24 horas num dia, 24 cervejas numa caixa. Coincidência?',
     'Quando li sobre os problemas que a bebida causa, deixei de ler.',
     'Coma merda! Milhões de moscas não podem estar erradas…',
     'Se um dia você sentir um vazio em você, coma que é fome!!!',
     'As mulheres perdidas são as mais procuradas.',
     'O que há de comum entre um bolo queimado, cerveja estourada e mulher grávida? Nada, mas se você tivesse '
     'tirado antes, nada disso teria acontecido…',
     'Se homossexualismo fosse normal, Deus teria criado Adão e Ivo.',
     'Beijo não mata a fome, mas abre o apetite…',
     'Mulheres são como traduções: as boas não são fiéis e as fiéis não são boas…',
     'Sogra é como onça: todos temos que preservar, mas ninguém quer ter em casa.',
     'Mulher feia é igual a ventania, só quebra galho.',
     'Em dia de tempestades e trovoadas, o local mais seguro é perto da sogra, não há raio que a parta!!',
     'O duro não é carregar o peso do chifre… é sustentar a vaca.',
     'Eu bebo pra ficar ruim mesmo, se fosse pra ficar bom, eu tomava remédio!',
     'O chifre é como o consórcio… quando você menos espera é contemplado!',
     'Casar é trocar a admiração de várias mulheres, pela crítica de uma só!!',
     'Nas horas difíceis da vida, você deve levantar a cabeça, estufar o peito e dizer de boca cheia: Agora fudeu!!!',
     'Não ria de tudo, pois quem acha tudo gozado é faxineira de motel…',
     'Se sua sogra é uma joia, nós temos a caixinha perfeita! Funerária Vá com Deus.',
     'O amor é como capim: você planta, ele cresce… aí vem uma vaca e acaba com tudo!',
     'Eu bebo pouco, mas este pouco me transforma em outra pessoa; e essa outra pessoa bebe pra caralho!!!',
     'O Brasil é um país geométrico…. tem problemas angulares, discutidos em mesas redondas, por um monte de '
     'bestas quadradas.',
     'Para que levar a vida a sério, se nós nascemos duma gozada?!',
     'Gaúcho que é gaúcho não navega na internet; atravessa a nado!',
     'O assaltante pede seu dinheiro ou sua vida; as mulheres querem os dois.',
     'Um homem de sucesso é o que ganha mais dinheiro do que sua mulher consegue gastar. Uma mulher de sucesso é a '
     'que consegue encontrar um homem desses.',
     'Sexo não tem nada a ver com amor. Tanto isso é verdade que o governo me fode há 51 anos e eu não sou apaixonado '
     'por ele…',
     'Gordinha é que nem Ferrari: quando sobe na balança vai de zero a cem em um segundo…',
     'Deus dai me paciência para aguentar meu chefe, porque se me der força eu bato nele!',
     'Aprenda uma coisa: o mundo não gira em torno de você. Só quando você bebe demais.',
     'Se um dia a vida lhe der as costas, passe a mão na bunda dela.',
     'Todo mundo tem cliente. Só traficante e analista de sistemas é que tem usuário.',
     'Os psiquiatras dizem que uma em cada quatro pessoas tem alguma deficiência mental. Fique de olho em três dos '
     'seus amigos. Se eles parecerem normais, o retardado é você!!',
     'Otário não é aquele que envia ou recebe SPAM, mas sim, quem os responde…',
     'Quando as luzes estão apagadas, todas as mulheres são bonitas.',
     'As mulheres são como vinho: com o passar dos anos, umas refinam, outras azedam. E as que azedam, é por falta '
     'de rolha.',
     'Alguns homens amam tanto suas mulheres, que para não as gastarem, preferem usar as dos outros.',
     'As nuvens são como chefes… quando desaparecem, o dia fica lindo!',
     'Se não puder ajudar, atrapalhe. Afinal, o importante é participar.',
     'Se você está se sentindo sozinho, abandonado, achando que ninguém liga para você… atrase um pagamento…',
     'Passar a mulher para trás é fácil, difícil é passar adiante!',
     'O natal é injusto, o peru morre e a missa é do galo.',
     'Se você é feio, pobre, burro e, mesmo assim, tem um monte de mulher dando em cima de você, só tem uma '
     'explicação: Você mora embaixo de um prostíbulo.',
     'Parente quando vem para sua casa é que nem peixe, passou de três dias começa a feder.',
     'Um aposentado tem entre as pernas outro aposentado.',
     'Estou mais perdido que filho da puta em dia dos pais.',
     'Peito de mulher é igual autorama, feito para criança mas só adulto brinca.',
     'O casamento, tal como é, é uma coisa estranha, mas afinal de contas, ainda não se achou coisa melhor.',
     'O motorista ideal para o Papa-Móvel é o Rubens Barrichello – finalmente ele poderia andar na frente do alemão, '
     'dirigindo devagar e com os brasileiros aplaudindo.',
     'Não leve a vida tão a sério, afinal, você não vai sair vivo dela mesmo.',
     'Solteiro é um sujeito que chega toda manhã ao trabalho vindo de uma direção diferente.',
     'Se eu não andasse de ônibus nos horários de pico, a minha vida sexual seria zero.',
     'Fantasia sexual é que nem cheiro de cocô: a gente só acha normal quando é da gente.',
     'Inglêiz eu não sei, maiz heim portuguêiz eu çôu fera.',
     'O mundo precisa de mais gênios humildes! Hoje em dia somos poucos…',
     'É melhor duas abelhas voando do que uma na mão.',
     'Se você não pode ajudar, atrapalhe! O importante é participar!',
     'Macho que é macho pega mulher feia; porque mulher bonita todo mundo quer pegar!',
     'Onde quer que você esteja, você sempre estará lá!',
     'A humanidade está perdendo seus maiores gênios… Aristóteles faleceu, Newton bateu as botas, Einstein morreu, '
     'e eu não estou passando muito bem hoje.',
     'Quando alguém lhe chamar de gordo não ligue, você é maior que tudo isso.',
     'Quando um não quer, dois não brigam, mas um apanha.',
     'Mulher de amigo meu é que nem travesseiro: só ponho a cabeça.',
     'Nas horas difíceis da vida, você deve levantar a cabeça, estufar o peito e dizer de boca cheia: Agora fudeu!!!',
     'Existem duas maneiras de tratar as mulheres. Até hoje ninguém descobriu quais são.',
     '12 de junho é o dia dos namorados; os outros 364 são nossos….',
     'Quem cedo madruga passa o dia com sono.',
     'Extra! Extra! Gêmeo tenta se suicidar e mata o irmão por engano.',
     'Canela: dispositivo para se encontrar móveis no escuro.',
     'Evite acidentes. Faça de propósito.',
     'O que o instrutor da escola de homens bomba disse para os alunos? “Prestem atenção que vou fazer só '
     'uma vez hein…',
     'É chato ser bonito. Mas é muito mais chato ser feio.'])

reflita = (
    ['da pessoa que você esta se tornando, evoluir leva tempo mas vale a pena.',
     'Enquanto as consequências de um erro ainda te afetarem, é sinal de que ele ainda não foi superado.',
     'A vida não oferece promessas nem garantias. Apenas possibilidades e oportunidades.',
     'Gosto que me digam a verdade. Eu decido se ela dói ou não.',
     'Existe dois tipos de dores no mundo: A dor que te machuca e a dor que te muda.',
     'Lembre-se que existem os finais felizes e os finais necessários.',
     'Enquanto você for o que os outros querem que você seja, você não será ninguém.',
     'Você sabe que está no caminho certo quando perde o interesse de olhar para trás.',
     'Ter problemas na vida é inevitável, ser derrotado por eles é opcional.',
     'Uma pessoa inteligente resolve um problema, um sábio o previne.',
     'Se você apagasse todos os erros do seu passado, você apagaria toda sabedoria do seu presente.',
     'A prepotência te faz forte por um dia, a humildade para sempre.',
     'Se todos soubessem o peso das palavras, dariam mais valor ao silêncio.',
     'Lembre-se: sempre haverá outra chance, outra amizade, outro amor ... mas nunca outra vida.',
     'Colecione momentos, não coisas.',
     'Pare de olhar para trás, você já sabe onde esteve, agora precisa saber onde vai.',
     'Preserve. Pessoas boas estão sendo extintas.',
     'Ninguém pode fazer com que você se sinta inferior sem o seu consentimento.',
     'Você é feliz, ou apenas sorri?',
     'Tudo é considerado impossível até acontecer.',
     'Nunca estrague o seu presente por um passado que não tem futuro.',
     'Você nunca chegará no próximo capítulo de sua vida se continuar relendo o anterior.',
     'Não há ventos favoráveis para aqueles que não sabem onde querem chegar.',
     'É melhor levar uma surra da sinceridade do que um abraço da falsidade.',
     'Tudo aquilo que é exagerado, desconfie. Inclusive bondade.',
     'O pior naufrágio é não partir.',
     'Acreditar é essencial, mas ter atitude é o que faz a diferença.',
     'Será que todos que dizem o que querem estão preparados para ouvir a verdade?',
     'Cada um pensa em mudar a humanidade, mas ninguém pensa em mudar a si mesmo.',
     'Aqueles que falam de você na sua ausência, é porque respeitam a sua presença.',
     'Aprenda a argumentar e nunca mais precisará ter razão.',
     'Não mude por causa de ninguém. Quem te ama te aceita, não te julga.',
     'Esqueça os tempos de aflição, mas nunca esqueça o que eles lhe ensinaram.',
     'Se você não tem motivos para sorrir, pelo menos não dê motivos para os outros chorarem.',
     'Se você morresse hoje, estaria orgulhoso pelo que andou fazendo no mundo?',
     'Eu preferiria ser um fracasso em algo que amo do que um sucesso em algo que odeio.',
     'O homem é mortal por seus temores e imortal por seus desejos.',
     'O que torna a ingenuidade tão graciosa é que ela não foi feita para durar.',
     'Quem diz que não pode ser feito nunca deve interromper aquele que está fazendo.',
     'A vida é muito curta para ser pequena.',
     'Se você não lutar por alguma coisa, será vencido por qualquer coisa.',
     'Tente mover o mundo. O primeiro passo será mover a si mesmo.',
     'Seja mais forte do que sua melhor desculpa.',
     'Aquele que não luta pelo futuro que quer, deve aceitar o futuro que vier.',
     'E que a sua coragem seja maior do que o seu medo.',
     'Um passo à frente e você não está mais no mesmo lugar.',
     'Dificuldades preparam pessoas comuns para destinos extraordinários.',
     'Se você esperar pelas condições perfeitas, nunca vai fazer nada.',
     'Desista de desistir.',
     'Mais vale a lágrima da derrota, do que a vergonha de não ter lutado.',
     'Aquele que tentou e não conseguiu, é superior àquele que não tentou.',
     'Tenha fé que sua história vai mudar. Grite bem alto e depois é só acreditar.',
     'Um dia vai dar certo, e quando der certo você vai rir de tudo que deu errado.',
     'Todo campeão foi um dia um competidor que se recusou a desistir.',
     'Se quer viver uma vida feliz, amarre-se a uma meta, não a pessoas nem a coisas.',
     'Nunca é tarde demais para ser aquilo que sempre se desejou ser.',
     'Acredite, corra atrás, a única coisa que existe entre você e o seu sonho é o seu medo.',
     'Nenhum obstáculo é tão grande se a sua vontade de vencer for maior.',
     'Já experimentou acreditar em você? Tente, você não faz ideia do que é capaz.',
     'Toda ação humana, quer se torne positiva ou negativa, precisa depender de motivação.',
     'Nada é difícil se for dividido em pequenas partes.',
     'Você precisa fazer aquilo que pensa que não é capaz de fazer.',
     'A gratidão é a memória do coração.',
     'Seja grato pelo agora. O que passou é lição aprendida.',
     'Tudo começou a dar certo quando eu parei de pedir chorando e comecei a agradecer sorrindo.',
     'Nenhum dever é mais importante do que a gratidão.',
     'Invejar é do queixoso e do doente. Agradecer é do que está satisfeito.',
     'Agradeço pela crítica mais severa apenas se ela permanecer imparcial.',
     'A melhor maneira de agradecer por um belo momento é desfrutá-lo plenamente.',
     'Não sei se o mundo é bom, mais ele ficou muito melhor quando você apareceu. Muito obrigado!',
     'Agradeço pela crítica mais severa apenas se ela permanecer imparcial.',
     'Agradeço por tudo que tenho. Agradecer é a arte de atrair coisas boas!',
     'Agradeço a Deus por ter você mesmo que apenas em meus pensamentos.',
     'Abra sua mente antes da boca.',
     'Das habilidades que o mundo sabe, essa é a que ele ainda faz melhor: dar voltas.',
     'Mais pessoas inteiras. Menos meias verdades.',
     'Sou responsável pelo que eu falo, não pelo que você entende.',
     'Sou exigente com a beleza. Ela tem que vir de dentro.',
     'Não deixe pra amanhã o que você pode deixar pra lá.',
     'A diferença entre o inteligente e o sábio, é que o sábio pensa a longo prazo.',
     'Podemos nos defender de um ataque, mas somos indefesos a um elogio.',
     'Não se fazem mais antigamentes como antes.',
     'Quanto maior o conhecimento menor o ego, quanto maior o ego menor o conhecimento.',
     'Lembre-se: o uso exagerado da língua pode atrofiar o cérebro.',
     'Um brinde aos nossos defeitos, porque com as nossas qualidades ninguém se importa mesmo.',
     'Valorize-se. É grátis!',
     'O que é pior: chegar ao fundo do poço ou continuar caindo?',
     'Evoluir é reconhecer nossos erros. Não para concertá-los, mas para não repetí-los.',
     'Inteligência sem ambição é um pássaro sem asas.',
     'A vantagem da honestidade é que a concorrência é pequena.',
     'Ontem eu era inteligente, queria mudar o mundo. Hoje eu sou sábio, estou mudando a mim mesmo.',
     'Há sempre alguma loucura no amor. Mas há sempre um pouco de razão na loucura.',
     'Exige muito de ti e espera pouco dos outros. Assim, evitarás muitos aborrecimentos.',
     'Os melhores conselhos são sempre os mais difíceis de seguir.',
     'Os opostos se atraem porque as diferenças se completam.',
     'Quando te chamarem de amador, lembre-se: amadores fizeram a Arca de Noé e profissionais fizeram o Titanic.',
     'Tornar o simples em complicado é fácil. Tornar o complicado em simples é criatividade.',
     'A diferença entre o veneno e o remédio é a dose.',
     'Primeiro a chuva, depois o arco-íris. Se acostume, a ordem é sempre essa.',
     'A sensação do "eu conquistei" é muito melhor que a sensação do "eu tenho".',
     'Se quiser que os seus sonhos tornem-se realidade, acorde!',
     'Um grama de exemplos, vale mais que uma tonelada de conselhos.',
     'Você pode descobrir mais sobre uma pessoa em uma hora de brincadeira do que em um ano de conversa.',
     'Duas coisas são infinitas: o universo e a estupidez humana.',
     'Triste época! É mais fácil desintegrar um átomo do que um preconceito.',
     'A experiência é uma escola onde são caras as lições, mas em nenhuma outra os tolos podem aprender.',
     'Se matamos uma pessoa somos assassinos. Se matamos milhões de homens, celebram-nos como heróis.',
     'A mente que se abre a uma nova idéia jamais voltará ao seu tamanho original.',
     'Até um relógio parado tem razão duas vezes ao dia.',
     'O único lugar onde o sucesso vem antes do trabalho é no dicionário.',
     'O caminho do sucesso não é fazer uma coisa 100 por cento melhor, mas fazer 100 coisas um por cento melhor.',
     'Qualquer fracassado lhe dirá que sucesso não passa de sorte.',
     'O sábio nunca diz tudo o que pensa, mas pensa sempre tudo o que diz.',
     'Não leve a vida tão a sério, afinal nem sairá vivo dela!',
     'Não há invenção mais rentável que a do conhecimento.',
     'A imaginação é mais importante que o conhecimento.',
     'Geralmente aqueles que sabem pouco falam muito e aqueles que sabem muito falam pouco.',
     'Nós somos aquilo que fazemos repetidamente. Excelência, então, não é um modo de agir, mas um hábito.',
     'A melhor maneira que o homem dispõe para se aperfeiçoar, é aproximar-se de Deus.',
     'O verdadeiro heroísmo consiste em persistir por mais um momento quando tudo parece perdido.',
     'Nem tudo que se enfrenta pode ser modificado, mas nada pode ser modificado até que seja enfrentado.',
     'Os que leem sabem muito, mas os que observam sabem muito mais.',
     'Quem comete uma injustiça é sempre mais infeliz que o injustiçado.',
     'Ainda pior que a convicção do não, e a incerteza do talvez, é a desilusão de um quase.',
     'Os livros não mudam o mundo, quem muda o mundo são as pessoas. Os livros só mudam as pessoas.',
     'A felicidade e a infelicidade vêm de nós próprios.',
     'A felicidade não consiste em adquirir nem em gozar, mas sim em nada desejar, consiste em ser livre.',
     'A paz, se possível, mas a verdade a qualquer preço.',
     'A pedido da vida, percorrerei toda extensão do Universo contido dentro do meu coração.',
     'A penicilina cura os homens, mas é o vinho que os torna felizes.',
     'Tudo o que somos nasce com nossos pensamentos. Em nossos pensamentos, fazemos o nosso mundo.',
     'A felicidade é a fruta final e perfeita da obediência às leis da vida.',
     'A ação nem sempre traz felicidade, mas não há felicidade sem ação.',
     'A adversidade desperta em nós capacidades que, em circunstâncias favoráveis, teriam ficado adormecidas.',
     'A fé é uma conquista difícil, que exige combates diários para ser mantida.',
     'Posso perdoar, mas esquecer é outra coisa.',
     'Não há ninguém, mesmo sem cultura, que não se torne poeta quando o Amor toma conta dele.',
     'Arte é aquilo em que o mundo se transformará, não aquilo que o mundo é.',
     'Aja de forma que seus princípios possam seguramente tornar-se lei para todos.',
     'Dar menos que o seu melhor é sacrificar o dom que recebeu.',
     'Torne-se um homem honesto e poderá estar certo que há menos um patife no mundo.',
     'O mais importante da vida não é a situação em que estamos, mas a direção para a qual nos movemos.',
     'Perca tempo na escolha de um amigo, mas perca ainda mais quando tiver de o trocar.'])

reflita_zueira = (
    ['Minha paciência é igual dinheiro, não tenho e quando tenho some rápido.',
     'Atenção, devido ao aumento da gasolina, da energia, do salário dos políticos e da corrupção, informamos que '
     'a "luz no fim do túnel" foi cortada.',
     'Hoje vou pro estado onde só tem mulher bonita... o estado de embriaguez.',
     'Claustrofobia: medo de lugares fechados. Exemplo: quando eu tô indo pro bar e sinto medo de ele estar fechado.',
     '- Soldado, não te vi na aula de camuflagem hoje. - Obrigado capitão.',
     '- Você sabia que as caixas pretas dos aviões na verdade são laranjas? - Não acredito ... não são caixas?',
     'Encontrei o seu nariz. Ele estava onde não foi chamado.',
     'O que é um terapeuta? São 1024 gigapeutas.',
     'Alguém sabe informar se o tempo no instagram, no facebook e no whatsapp conta pra aposentadoria?',
     'Paciência é tudo ... tudo que eu não tenho.',
     '- Tenho uma boa e uma má notícia pra você. A má é que vamos ter que amputar sua perna esquerda. - E qual é a '
     'boa? - A boa é que você vai começar o ano com o pé direito.',
     'A vida é igual Pilates. Se tá fácil, tá errado.',
     '- Professor, o que vai cair na prova? - Lágrimas.',
     'Não é preguiça. É redirecionamento estratégico de energia vital.',
     'Me passe o número da sua opinião, quem sabe um dia eu ligue pra ela.',
     'Falam que o álcool causa a morte de muitos, mas não falam quantos nasceram por causa dele. (Aristólitros)',
     'Não é que eu tenha medo de morrer. Só não quero estar lá quando isso acontecer.',
     'Fórmula para não faltar madeira no mundo: basta o Pinóquio virar político. (Jufras Menhal)',
     'As aparências enganam ... e em alguns casos assustam.',
     'Li que fumar fazia mal, parei de fumar. Li que beber fazia mal, parei de beber. Li que fazer sexo fazia '
     'mal. Parei de ler.',
     'Trabalhar nunca matou ninguém, mas ... pra que arriscar?',
     '-Mamãe,o que é um orgasmo? -Não sei meu filho, pergunte pro seu pai.',
     'A risada é o melhor remédio, mas se você está dando risada sem nenhum motivo, talvez você esteja precisando '
     'tomar outro tipo de remédio.',
     'É muito triste quando se é rico, bonito e sensual e aí vem o despertador e acaba com tudo.',
     'Dica de beleza: Ande sempre com um amigo mais feio que você.',
     'Se as pessoas dormem de conchinha, será que as conchas dormem de pessoinha?',
     'Sabe o que acontece quando você esfrega uma lâmpada embaixo d´água? Aparece um Hidrogênio.',
     'Por um mundo onde as pessoas torrem as minhas calorias e não a minha paciência.',
     'Se quem ama cuida, muita gente deve me amar. Porque o que tem de pessoas cuidando da minha vida, não '
     'é brincadeira.',
     'Só não morro de preguiça porque tenho preguiça de morrer.',
     '- Mãe, me disseram na escola que eu sou muito distraído. - Menino, presta atenção, eu não sou sua mãe. Sua '
     'casa é a do lado!',
     'Os ursos polares adoram o frio. Os bipolares às vezes adoram, às vezes não...',
     'Herança é aquilo que os mortos deixam para que os vivos se matem.',
     'Dizem que todo mundo merece uma segunda chance. Acho que eu já ficaria satisfeito se me dessem a primeira.',
     'Quer ganhar milhões de seguidores? Cutuque uma colmeia de abelhas e saia correndo.',
     '– Isso foi um relâmpago? – Não amigo, foi o Google Earth tirando foto da terra com flash.',
     'Tô correndo atrás do prejuízo, mas parece que ele é Queniano.',
     'Malandro é o Canguru que já nasce com o Bolsa Família.',
     'Antes de falar, ouça. Antes de agir, pense. Antes de desistir, tente. Antes de cagar, veja se tem papel.',
     'Se você é feio, pobre, burro e, mesmo assim, tem um monte de mulher dando em cima de você, só tem uma '
     'explicação. Você mora embaixo de uma zona.',
     'O sol nasce, a bicicleta anda, o gato mia e o urso panda.',
     'Quando sua mulher fica grávida, todos alisam a barriga dela e dizem "parabéns". Mas ninguém apalpa seu saco '
     'e diz "bom trabalho".',
     'Mãe, posso usar sutiã? -Não. -Por favor mãe. -Não. -Mas eu já tenho 15 anos mãe. -Já disse que não Paulo André.',
     'Percebi que a bebida exalta a minha beleza. Sempre que minha mulher me vê bêbado ela diz: "Bonito, hein!"',
     'Estudos mostram que 1 em cada 4 pessoas tem alguma deficiência mental. Fique de olho em três dos seus amigos. '
     'Se eles parecerem normais, o retardado é você!',
     'Viva cada dia como se fosse o último, um dia você acerta.',
     'Quem dá aos pobres, tem que pagar o motel.',
     'O cara era tão magro que o chuveiro dele só tinha um furo!',
     'Se o Xororó fosse dono de uma sorveteria, nela teria uma sobremesa chamada Sundae Junior.',
     'Amor não é uma coisa que mexe por dentro e deixa marcas quando passa. O nome disso é diarréia.',
     'O sábio tem algo a dizer e o idiota tem que dizer algo.',
     'Se a vida lhe virar as costas, passe a mão na bunda dela.',
     'Meu calendário já está chegando na metade, acho que ano que vem vou ter que comprar outro.',
     'Por que "já" quer dizer agora, e "já, já" quer dizer daqui a pouco?',
     'O importante não é saber, mas sim ter o telefone de quem sabe.',
     'Não existem ideias idiotas, existem ideias na cabeça de idiotas.',
     'Não bebo, não fumo e não falo besteira ... mas às vezes minto!',
     'As últimas palavras de um peixe: Estou frito!',
     'Como é que a placa (Proibido pisar na grama) foi colocada lá?',
     'O sonho não acabou, ainda temos pão doce, maria-mole e queijadinha.',
     'Não roube, o governo não gosta de concorrência.',
     'Quando o relógio foi inventado, como sabiam que horas eram?',
     'Se o vinho é líquido, como pode ser seco ?',
     'Como é que a gente sabe que a carne de chester é de chester se nunca ninguém viu um chester?',
     'Em Portugal os restaurantes fecham para almoço.',
     'Acabe com os probemas do seu computador ... delete seu Windows!',
     'Gênio em Portugal inventou a lanterna de luz solar.',
     'Foram felizes durante 25 anos ... aí se encontraram.',
     'Eu achei uma solução, agora só falta descobrir qual é o problema.',
     'O trabalho em equipe é ótimo, pois permite que você ponha a culpa em outra pessoa.',
     'Dúvida ecológica: O Hulk faz fotossíntese?',
     'Se tempo fosse dinheiro, meu relógio seria milionário!',
     'A vida é imprevisível ... coma a sobremesa antes.',
     'Nunca brinque com fogo ... ele é chato e não sabe brincar!',
     'Um bom músico sempre tira boas notas.',
     'Se o videogame atrapalha os estudos, pare de estudar.'])
