CARDS = [{'nome': 'Castle of Dark Illusions', 'foto': 'https://i.imgur.com/ldZhcpF.jpg'},
         {'nome': 'Unexpected Dai', 'foto': 'https://i.imgur.com/qTQGUnC.jpg'},
         {'nome': 'Misfortune', 'foto': 'https://i.imgur.com/AMkZVPP.jpg'},
         {'nome': 'Gem-Knight Fusion', 'foto': 'https://i.imgur.com/LVYUSb3.jpg'},
         {'nome': 'Ultimaya Tzolkin', 'foto': 'https://i.imgur.com/7pdlp88.jpg'},
         {'nome': 'Time-Space Trap Hole', 'foto': 'https://i.imgur.com/G6s1EEq.jpg'},
         {'nome': 'Trap Reclamation', 'foto': 'https://i.imgur.com/3uXhydv.jpg'},
         {'nome': 'Book of Life', 'foto': 'https://i.imgur.com/ak0NCdd.jpg'},
         {'nome': 'Reflect Bounder', 'foto': 'https://i.imgur.com/2BHrKv4.jpg'},
         {'nome': 'Curse of Royal', 'foto': 'https://i.imgur.com/XTG6UZP.jpg'},
         {'nome': 'Ryu-Ran', 'foto': 'https://i.imgur.com/DZUKU2L.jpg'},
         {'nome': 'Fake Trap', 'foto': 'https://i.imgur.com/LTU6XfG.jpg'},
         {'nome': 'Worm Solid', 'foto': 'https://i.imgur.com/hJtAu2i.jpg'},
         {'nome': 'Forbidden apocrypha', 'foto': 'https://i.imgur.com/vSiuMed.jpg'},
         {'nome': 'Change of Heart', 'foto': 'https://i.imgur.com/lYUdXIY.jpg'},
         {'nome': 'Chronomaly City Babylon', 'foto': 'https://i.imgur.com/0tilTLc.jpg'},
         {'nome': 'Dark Energy', 'foto': 'https://i.imgur.com/wd4BSub.jpg'},
         {'nome': 'Shaddoll Core', 'foto': 'https://i.imgur.com/HyBsaz4.jpg'},
         {'nome': 'Full Force Virus', 'foto': 'https://i.imgur.com/1n4wm8g.jpg'},
         {'nome': 'Firewall Dragon', 'foto': 'https://i.imgur.com/4zHPxco.jpg'},
         {'nome': 'Galaxy Cyclone', 'foto': 'https://i.imgur.com/ws5X0gu.jpg'},
         {'nome': 'Black Luster Soldier', 'foto': 'https://i.imgur.com/PvoOTVv.jpg'},
         {'nome': 'Storming Mirror Force', 'foto': 'https://i.imgur.com/52Vr5qk.jpg'},
         {'nome': 'Vanitys Emptiness', 'foto': 'https://i.imgur.com/r5wcxK2.jpg'},
         {'nome': 'Uria, Lord of Searing Flames', 'foto': 'https://i.imgur.com/4DlLfmO.jpg'},
         {'nome': 'Red-Eyes Fusion', 'foto': 'https://i.imgur.com/kLkWjWS.jpg'},
         {'nome': 'Infected Mail', 'foto': 'https://i.imgur.com/fkOQotO.jpg'},
         {'nome': 'Skull Lair', 'foto': 'https://i.imgur.com/PY0DwoB.jpg'},
         {'nome': 'Shadow Toon', 'foto': 'https://i.imgur.com/Y25x5jy.jpg'},
         {'nome': 'Hane-Hane', 'foto': 'https://i.imgur.com/x4mvmgz.jpg'},
         {'nome': 'Field Barrier', 'foto': 'https://i.imgur.com/0a2EMyV.jpg'},
         {'nome': 'Mechanicalchaser', 'foto': 'https://i.imgur.com/Nj2TFwa.jpg'},
         {'nome': 'Shien\'s Spy', 'foto': 'https://i.imgur.com/mX5Hvoi.jpg'},
         {'nome': 'Cosmic Cyclone', 'foto': 'https://i.imgur.com/yA0LIBt.jpg'},
         {'nome': 'Lyrilusc - Recital Starling', 'foto': 'https://i.imgur.com/AhO3eES.jpg'},
         {'nome': 'The First Monarch', 'foto': 'https://i.imgur.com/NgE0vWS.jpg'},
         {'nome': 'Poison of the Old Man', 'foto': 'https://i.imgur.com/YxWCdAT.jpg'},
         {'nome': 'Graceful Tear', 'foto': 'https://i.imgur.com/cJk4FLb.jpg'},
         {'nome': 'LaLa Li-Oon', 'foto': 'https://i.imgur.com/4pGLI1l.jpg'},
         {'nome': 'Eulers Circuit', 'foto': 'https://i.imgur.com/GcnbZel.jpg'},
         {'nome': 'Kaminari Attack', 'foto': 'https://i.imgur.com/ePmPEWm.jpg'},
         {'nome': 'Blackwing - Gofu the Vague Shadow', 'foto': 'https://i.imgur.com/yrsnGhv.jpg'},
         {'nome': 'Beast Rage', 'foto': 'https://i.imgur.com/aojxN18.jpg'},
         {'nome': 'Infinite Impermanence', 'foto': 'https://i.imgur.com/2bUGaz6.jpg'},
         {'nome': 'Ancient Rules', 'foto': 'https://i.imgur.com/5sDgc5H.jpg'},
         {'nome': 'Barrier Statue of the Torrent', 'foto': 'https://i.imgur.com/3uKEn0P.jpg'},
         {'nome': 'Gradius', 'foto': 'https://i.imgur.com/YVSxQXL.jpg'},
         {'nome': 'Fortissimo', 'foto': 'https://i.imgur.com/DxRUHBg.jpg'},
         {'nome': 'D/D Savant Kepler', 'foto': 'https://i.imgur.com/fRGacpu.jpg'},
         {'nome': 'Barkions Bark', 'foto': 'https://i.imgur.com/ihMHJ8k.jpg'},
         {'nome': 'SPYRAL Sleeper', 'foto': 'https://i.imgur.com/eO2ShGk.jpg'},
         {'nome': 'Skull dice', 'foto': 'https://i.imgur.com/ahiRvLG.jpg'},
         {'nome': 'Hero Flash!!', 'foto': 'https://i.imgur.com/ExV3LKl.jpg'},
         {'nome': 'Frightfur Tiger', 'foto': 'https://i.imgur.com/ouMBOiJ.jpg'},
         {'nome': 'PSY-Frame Circuit', 'foto': 'https://i.imgur.com/9LvFNpY.jpg'},
         {'nome': 'Daigusto Emeral', 'foto': 'https://i.imgur.com/X5ROzVF.jpg'},
         {'nome': 'Virgil, Rock Star of the Burning Abyss', 'foto': 'https://i.imgur.com/2qvmdGY.jpg'},
         {'nome': 'Ronintoadin', 'foto': 'https://i.imgur.com/BHNPn7R.jpg'},
         {'nome': 'Dragon Treasure', 'foto': 'https://i.imgur.com/8gWdtwT.jpg'},
         {'nome': 'Clara & Rushka, the Ventriloduo', 'foto': 'https://i.imgur.com/jJjOCj7.jpg'},
         {'nome': 'Decode Talker', 'foto': 'https://i.imgur.com/qyz3tvv.jpg'},
         {'nome': 'Key Mace', 'foto': 'https://i.imgur.com/bGchdVc.jpg'},
         {'nome': 'Wetlands', 'foto': 'https://i.imgur.com/XPDPPnH.jpg'},
         {'nome': 'Constelar Praesepe', 'foto': 'https://i.imgur.com/CyY8Zxw.jpg'},
         {'nome': 'Hyosube', 'foto': 'https://i.imgur.com/SVVKYam.jpg'},
         {'nome': 'Blue-Eyes Twin Burst Dragon', 'foto': 'https://i.imgur.com/HgJZmGR.jpg'},
         {'nome': 'Skull Knight', 'foto': 'https://i.imgur.com/s489rD0.jpg'},
         {'nome': 'Legendary Six Samurai - Kageki', 'foto': 'https://i.imgur.com/ALO3XMn.jpg'},
         {'nome': 'Naturia Barkion', 'foto': 'https://i.imgur.com/PwMrX0O.jpg'},
         {'nome': 'Buster Blader, the Destruction Swordmaster', 'foto': 'https://i.imgur.com/qMzqFfq.jpg'},
         {'nome': 'Overload Fusion', 'foto': 'https://i.imgur.com/QZIXtlk.jpg'},
         {'nome': 'Knightmare Mermaid', 'foto': 'https://i.imgur.com/oBHWXnj.jpg'},
         {'nome': 'Shaddoll Beast', 'foto': 'https://i.imgur.com/t6Ru7da.jpg'},
         {'nome': 'Skypalace Gangaridai', 'foto': 'https://i.imgur.com/uPY7l3W.jpg'},
         {'nome': 'Seven Tools of the Bandit', 'foto': 'https://i.imgur.com/NrwHl4j.jpg'},
         {'nome': 'Trap Hole', 'foto': 'https://i.imgur.com/bSSRNrz.jpg'},
         {'nome': 'Performapal Turn Toad', 'foto': 'https://i.imgur.com/HhRhQdJ.jpg'},
         {'nome': 'SPYRAL GEAR - Drone', 'foto': 'https://i.imgur.com/nMbXSyc.jpg'},
         {'nome': 'Chaos Emperor, the Dragon of Armageddon', 'foto': 'https://i.imgur.com/1rMNDj6.jpg'},
         {'nome': 'Card Guard', 'foto': 'https://i.imgur.com/KzFuPAo.jpg'},
         {'nome': 'Michael, the Arch-Lightsworn', 'foto': 'https://i.imgur.com/Q8f6Daj.jpg'},
         {'nome': 'Elemental Hero Neo-Bubbleman', 'foto': 'https://i.imgur.com/Mh89oDq.jpg'},
         {'nome': 'Mystical Space Typhoon', 'foto': 'https://i.imgur.com/rjfHpqy.jpg'},
         {'nome': 'Soul Release', 'foto': 'https://i.imgur.com/GXjJJPr.jpg'},
         {'nome': 'Toon Briefcase', 'foto': 'https://i.imgur.com/FAD1GOJ.jpg'},
         {'nome': 'El Shaddoll Fusion', 'foto': 'https://i.imgur.com/vDKH8fy.jpg'},
         {'nome': 'Schwarzschild Limit Dragon', 'foto': 'https://i.imgur.com/kxYkaFw.jpg'},
         {'nome': 'Tornado Dragon', 'foto': 'https://i.imgur.com/0u0uIc7.jpg'},
         {'nome': 'Secret Six Samurai - Genba', 'foto': 'https://i.imgur.com/WcugRi0.jpg'},
         {'nome': 'Cloak and Dagger', 'foto': 'https://i.imgur.com/KNqDiO7.jpg'},
         {'nome': 'Outer Entity Nyarla', 'foto': 'https://i.imgur.com/mLAwv1h.jpg'},
         {'nome': 'Flashbang', 'foto': 'https://i.imgur.com/zmBSxVR.jpg'},
         {'nome': 'Obelisk the Tormentor', 'foto': 'https://i.imgur.com/Z9joLyX.jpg'},
         {'nome': 'The Winged Dragon of Ra', 'foto': 'https://i.imgur.com/Oz66CeS.jpg'},
         {'nome': 'Slifer the Sky Dragon', 'foto': 'https://i.imgur.com/e2QU4uq.jpg'},
         {'nome': 'The Winged Dragon of Ra - Sphere Mode', 'foto': 'https://i.imgur.com/MTKMEgO.jpg'},
         {'nome': 'Psychic Feel Zone', 'foto': 'https://i.imgur.com/VlOUPji.jpg'},
         {'nome': 'Luster Dragon', 'foto': 'https://i.imgur.com/fkNB2mn.jpg'},
         {'nome': 'Horus Black Flame Dragon LV6', 'foto': 'https://i.imgur.com/vweGpUS.jpg'},
         {'nome': 'Chaos Trap Hole', 'foto': 'https://i.imgur.com/9n16wRD.jpg'},
         {'nome': 'Cyberse Witch', 'foto': 'https://i.imgur.com/QXtlwtO.jpg'},
         {'nome': 'Raigeki', 'foto': 'https://i.imgur.com/hLNcmQW.jpg'},
         {'nome': 'Waboku', 'foto': 'https://i.imgur.com/HIxmV8B.jpg'},
         {'nome': 'Swords of Concealing Light', 'foto': 'https://i.imgur.com/5kqGj59.jpg'},
         {'nome': 'Dragonic Diagram', 'foto': 'https://i.imgur.com/knanPpe.jpg'},
         {'nome': 'Vector Scare Archfiend', 'foto': 'https://i.imgur.com/j77IdZC.jpg'},
         {'nome': 'Steel Scorpion', 'foto': 'https://i.imgur.com/djumtgy.jpg'},
         {'nome': 'Trap Eater', 'foto': 'https://i.imgur.com/KGrfXbZ.jpg'},
         {'nome': 'Wall of Illusion', 'foto': 'https://i.imgur.com/3uduCq8.jpg'},
         {'nome': 'Book of Moon', 'foto': 'https://i.imgur.com/iivXcmw.jpg'},
         {'nome': 'SatellarKnight Altair', 'foto': 'https://i.imgur.com/wDVgoNB.jpg'},
         {'nome': 'One for One', 'foto': 'https://i.imgur.com/QVnMNAr.jpg'},
         {'nome': 'Symbol of Friendship', 'foto': 'https://i.imgur.com/1ImUf9a.jpg'},
         {'nome': 'Princess Curran', 'foto': 'https://i.imgur.com/Ypb4Pgb.jpg'},
         {'nome': 'Light of Redemption', 'foto': 'https://i.imgur.com/OKxK0TP.jpg'},
         {'nome': 'Xyz Reflect', 'foto': 'https://i.imgur.com/x2tPhvM.jpg'},
         {'nome': 'Water Omotics', 'foto': 'https://i.imgur.com/7YPbyus.jpg'},
         {'nome': 'Interrupt Resistor', 'foto': 'https://i.imgur.com/KVN4S5V.jpg'},
         {'nome': 'Ojamassimilation', 'foto': 'https://i.imgur.com/w1Yj4o4.jpg'},
         {'nome': 'Marauding Captain', 'foto': 'https://i.imgur.com/qbXBX2g.jpg'},
         {'nome': 'Galaxy-Eyes Cipher Blade', 'foto': 'https://i.imgur.com/BUDhmXu.jpg'},
         {'nome': 'A Rival Apears!', 'foto': 'https://i.imgur.com/Pn8PRht.jpg'},
         {'nome': 'Majespecter Tempest', 'foto': 'https://i.imgur.com/CR358RI.jpg'},
         {'nome': 'The Legendary Fisherman', 'foto': 'https://i.imgur.com/iAlvbeE.jpg'},
         {'nome': 'Knightmare Phoenix', 'foto': 'https://i.imgur.com/IPaLZAc.jpg'},
         {'nome': 'White Aura Whale', 'foto': 'https://i.imgur.com/8JzUcml.jpg'},
         {'nome': 'Cyber Valley', 'foto': 'https://i.imgur.com/0Qpojjv.jpg'},
         {'nome': 'Raidraptor - Fuzzy Lanius', 'foto': 'https://i.imgur.com/ih0PgzM.jpg'},
         {'nome': 'Sword of the Soul-Eater', 'foto': 'https://i.imgur.com/8YUp0IT.jpg'},
         {'nome': 'Topologic Bomber Dragon', 'foto': 'https://i.imgur.com/lj14RBa.jpg'},
         {'nome': 'Doomkaiser Dragon', 'foto': 'https://i.imgur.com/pGQ8Wp1.jpg'},
         {'nome': 'Gaia the Fierce Knight', 'foto': 'https://i.imgur.com/0b0TToH.jpg'},
         {'nome': 'Crystal Beast Sapphire Pegasus', 'foto': 'https://i.imgur.com/Z2UZu60.jpg'},
         {'nome': 'Lector Pendulum, the Dracoverlord', 'foto': 'https://i.imgur.com/fEMkpXO.jpg'},
         {'nome': 'Chocolate Magician Girl', 'foto': 'https://i.imgur.com/nc73roB.jpg'},
         {'nome': 'Goyo Guardian', 'foto': 'https://i.imgur.com/Ci23pKf.jpg'},
         {'nome': 'Noble Arms of Destiny', 'foto': 'https://i.imgur.com/nlsHVXg.jpg'},
         {'nome': 'Naturia Sunflower', 'foto': 'https://i.imgur.com/8IAyvLC.jpg'},
         {'nome': 'Milus Radiant', 'foto': 'https://i.imgur.com/H7GOMOG.jpg'},
         {'nome': 'Hip Hoshiningen', 'foto': 'https://i.imgur.com/hhQhXhD.jpg'},
         {'nome': 'Niwatori', 'foto': 'https://i.imgur.com/sU53hqn.jpg'},
         {'nome': 'Stellarknight Constellar Diamond', 'foto': 'https://i.imgur.com/4Ksvmwx.jpg'},
         {'nome': 'Metal Dragon', 'foto': 'https://i.imgur.com/JBxK74l.jpg'},
         {'nome': 'Cagna, Malebranche of the Burning Abyss', 'foto': 'https://i.imgur.com/71avAUw.jpg'},
         {'nome': 'Destiny Hero - Malicious', 'foto': 'https://i.imgur.com/4J9oCN3.jpg'},
         {'nome': 'D.D.R. - Different Dimension Reincarnation', 'foto': 'https://i.imgur.com/2vcP7EZ.jpg'},
         {'nome': 'Jet Synchron', 'foto': 'https://i.imgur.com/wCaxSaM.jpg'},
         {'nome': 'Caius the Shadow Monarch', 'foto': 'https://i.imgur.com/sRXftFE.jpg'},
         {'nome': 'Holactie the Creator of Light', 'foto': 'https://i.imgur.com/jRKPxyo.jpg'},
         {'nome': 'Jurassic World', 'foto': 'https://i.imgur.com/Vjzy46z.jpg'},
         {'nome': 'Deskbot 005', 'foto': 'https://i.imgur.com/xT3BROZ.jpg'},
         {'nome': 'Frightfur Leo', 'foto': 'https://i.imgur.com/x7DDvtZ.jpg'},
         {'nome': 'Number 42: Galaxy Tomahawk', 'foto': 'https://i.imgur.com/UohHf8i.jpg'},
         {'nome': 'Leogun', 'foto': 'https://i.imgur.com/AKpeskI.jpg'},
         {'nome': 'Frightfur Wolf', 'foto': 'https://i.imgur.com/5OJ9a52.jpg'},
         {'nome': 'Amazoness Baby Tiger', 'foto': 'https://i.imgur.com/Indkbfa.jpg'},
         {'nome': 'Tour Guide From the Underworld', 'foto': 'https://i.imgur.com/zs3EpsR.jpg'},
         {'nome': "Shien's Castle of Mist", 'foto': 'https://i.imgur.com/oK7gtB9.jpg'},
         {'nome': 'Invoked Elysium', 'foto': 'https://i.imgur.com/aYkX6k3.jpg'},
         {'nome': 'Lunalight Black Sheep', 'foto': 'https://i.imgur.com/aVcfUgN.jpg'},
         {'nome': 'Kozmoll Dark Lady', 'foto': 'https://i.imgur.com/WeR803y.jpg'},
         {'nome': 'Kozmouring', 'foto': 'https://i.imgur.com/OUvjeVM.jpg'},
         {'nome': 'King of Feral Imps', 'foto': 'https://i.imgur.com/FZk6CCK.jpg'},
         {'nome': 'Madolche Magileine', 'foto': 'https://i.imgur.com/c57PdnE.jpg'},
         {'nome': 'Lunalight Blue Cat', 'foto': 'https://i.imgur.com/KOaYENG.jpg'},
         {'nome': 'Harpie Lady Sisters', 'foto': 'https://i.imgur.com/XummNP4.jpg'},
         {'nome': 'Prime Material Dragon', 'foto': 'https://i.imgur.com/pWobYut.jpg'},
         {'nome': 'B. Skull Dragon', 'foto': 'https://i.imgur.com/XOshY7s.jpg'},
         {'nome': 'World Suppression', 'foto': 'https://i.imgur.com/vqIgPCl.jpg'},
         {'nome': 'Invoked Purgatrio', 'foto': 'https://i.imgur.com/O11vAyi.jpg'},
         {'nome': 'Treeborn Frog', 'foto': 'https://i.imgur.com/8jpIOg4.jpg'},
         {'nome': 'Cyber Network', 'foto': 'https://i.imgur.com/242bk3J.jpg'},
         {'nome': 'Unizong Tune', 'foto': 'https://i.imgur.com/sFGHwyi.jpg'},
         {'nome': 'Nuvia the Wicked', 'foto': 'https://i.imgur.com/L7qzOKI.jpg'},
         {'nome': 'Qliphort Stealth', 'foto': 'https://i.imgur.com/TcpCtRw.jpg'},
         {'nome': 'Crystron Quariongandrax', 'foto': 'https://i.imgur.com/fKbuQmq.jpg'},
         {'nome': 'Stygian Street Patrol', 'foto': 'https://i.imgur.com/1sUGv8s.jpg'},
         {'nome': 'Heavy Freight Train Derricrane', 'foto': 'https://i.imgur.com/cJGVJxV.jpg'},
         {'nome': 'Exodius the Ultimate Forbidden Lord', 'foto': 'https://i.imgur.com/bzXXRYE.jpg'},
         {'nome': 'Great Moth', 'foto': 'https://i.imgur.com/9yDKUpf.jpg'},
         {'nome': 'Elemental Hero Honest Neos', 'foto': 'https://i.imgur.com/Qeivwz2.jpg'},
         {'nome': 'Dark Grepher', 'foto': 'https://i.imgur.com/gDhC4Wd.jpg'},
         {'nome': 'Ash Blossom & Joyous Spring', 'foto': 'https://i.imgur.com/1QLkrYQ.jpg'},
         {'nome': 'Unity', 'foto': 'https://i.imgur.com/qyFIYFf.jpg'},
         {'nome': 'Mystical Elf', 'foto': 'https://i.imgur.com/KgRnxXv.jpg'},
         {'nome': 'Toon World', 'foto': 'https://i.imgur.com/MBkTPqM.jpg'},
         {'nome': 'Zoodiac Hammerkong', 'foto': 'https://i.imgur.com/7JdVwLV.jpg'},
         {'nome': 'Toon Attack Goblin Force', 'foto': 'https://i.imgur.com/JK5eVz7.jpg'},
         {'nome': 'Noble Arms - Gallatin', 'foto': 'https://i.imgur.com/DyIrn4U.jpg'},
         {'nome': 'Blackwing - Zephyros the Elite', 'foto': 'https://i.imgur.com/XoD05kp.jpg'},
         {'nome': 'Legendary Shadow of the Six Samurai', 'foto': 'https://i.imgur.com/5oc0WB2.jpg'},
         {'nome': 'Sectarian of Secrets', 'foto': 'https://i.imgur.com/rkvViBI.jpg'},
         {'nome': 'Evenly Matched', 'foto': 'https://i.imgur.com/L3MKBO7.jpg'},
         {'nome': 'Mind Crush', 'foto': 'https://i.imgur.com/5Hd0fRF.jpg'},
         {'nome': 'Odd-Eyes Pendulum Dragon', 'foto': 'https://i.imgur.com/PSG5CjM.jpg'},
         {'nome': "Gravekeeper's Servant", 'foto': 'https://i.imgur.com/DQqHlfc.jpg'},
         {'nome': 'Call of the Grave', 'foto': 'https://i.imgur.com/XfqtpnY.jpg'},
         {'nome': 'Wall of Revealing Light', 'foto': 'https://i.imgur.com/JwdEhdA.jpg'},
         {'nome': 'Lady of Faith', 'foto': 'https://i.imgur.com/94XUNJ6.jpg'},
         {'nome': 'Elder Entity Norden', 'foto': 'https://i.imgur.com/MtZxMsS.jpg'},
         {'nome': 'Introduction to Gallantry', 'foto': 'https://i.imgur.com/qisSMlz.jpg'},
         {'nome': 'Zera the Mant', 'foto': 'https://i.imgur.com/wRMfhKO.jpg'},
         {'nome': 'Gemini Elf', 'foto': 'https://i.imgur.com/JhE84LU.jpg'},
         {'nome': 'Space Cyclone', 'foto': 'https://i.imgur.com/WMyhQ9n.jpg'},
         {'nome': 'Performapal Partnaga', 'foto': 'https://i.imgur.com/UKztPPg.jpg'},
         {'nome': 'Vector Pendulum, the Dracoverlord', 'foto': 'https://i.imgur.com/Xk4VuIN.jpg'},
         {'nome': 'Dedication Through Light and Darkness', 'foto': 'https://i.imgur.com/3WdOzzO.jpg'},
         {'nome': 'Floodgate Trap Hole', 'foto': 'https://i.imgur.com/3cH1amS.jpg'},
         {'nome': 'Twin-Barrel Dragon', 'foto': 'https://i.imgur.com/N6eKGe8.jpg'},
         {'nome': 'Ancient Gear Fortress', 'foto': 'https://i.imgur.com/Xt48Sb6.jpg'},
         {'nome': 'Premature Burial', 'foto': 'https://i.imgur.com/Mc59B87.jpg'},
         {'nome': 'Dimensional Prison', 'foto': 'https://i.imgur.com/QHgLXtk.jpg'},
         {'nome': 'Upstart Goblin', 'foto': 'https://i.imgur.com/wXV2UUV.jpg'},
         {'nome': 'Danger! Nessie!', 'foto': 'https://i.imgur.com/UpmkGy3.jpg'},
         {'nome': 'Toon Roolback', 'foto': 'https://i.imgur.com/g3OkncI.jpg'},
         {'nome': 'Supreme King Dragon Clear Wing', 'foto': 'https://i.imgur.com/O68bfVl.jpg'},
         {'nome': 'Summoned Skull', 'foto': 'https://i.imgur.com/S1Y6rW5.jpg'},
         {'nome': 'Nobleman of Crossout', 'foto': 'https://i.imgur.com/YqDTcQV.jpg'},
         {'nome': 'Stuffed Animal', 'foto': 'https://i.imgur.com/84yvNXa.jpg'},
         {'nome': 'Royal Magical Library', 'foto': 'https://i.imgur.com/78rbVm4.jpg'},
         {'nome': 'Secret Six Samurai - Fuma', 'foto': 'https://i.imgur.com/MwyJX5I.jpg'},
         {'nome': "Wee Witch's Apprentice", 'foto': 'https://i.imgur.com/YLSOkMw.jpg'},
         {'nome': 'Breaker the Magical Warrior', 'foto': 'https://i.imgur.com/ULXKpy4.jpg'},
         {'nome': 'Defenders Intersect', 'foto': 'https://i.imgur.com/RgLXSAX.jpg'},
         {'nome': "Dragon's Mirror", 'foto': 'https://i.imgur.com/8sAS8Uo.jpg'},
         {'nome': 'Chthonian Polymer', 'foto': 'https://i.imgur.com/doNXANP.jpg'},
         {'nome': "Magician's Robe", 'foto': 'https://i.imgur.com/qIhK8Nz.jpg'},
         {'nome': 'Mekk-Knight of the Morning Star', 'foto': 'https://i.imgur.com/N2GH4C5.jpg'},
         {'nome': 'Crusadia Magius', 'foto': 'https://i.imgur.com/7V6Mnb5.jpg'},
         {'nome': 'Xiangke Magician', 'foto': 'https://i.imgur.com/oKE91Nz.jpg'},
         {'nome': 'Swords of Revealing Light', 'foto': 'https://i.imgur.com/B5F7SI2.jpg'},
         {'nome': 'Wisdom-Eye Magician', 'foto': 'https://i.imgur.com/xcimQD5.jpg'},
         {'nome': 'Pentestag', 'foto': 'https://i.imgur.com/1NHX4vO.jpg'},
         {'nome': 'Panzer Dragon', 'foto': 'https://i.imgur.com/PG767yg.jpg'},
         {'nome': 'Card Destruction', 'foto': 'https://i.imgur.com/eCndbrd.jpg'},
         {'nome': 'Six Samurai United', 'foto': 'https://i.imgur.com/ChsDtDA.jpg'},
         {'nome': 'Black Luster Soldier - Envoy of the Beginning', 'foto': 'https://i.imgur.com/5wivqeR.jpg'},
         {'nome': 'Topologic Trisbaena', 'foto': 'https://i.imgur.com/yatQNNO.jpg'},
         {'nome': 'Fluffal Wings', 'foto': 'https://i.imgur.com/8GmxcpE.jpg'},
         {'nome': 'Dragonic Tatics', 'foto': 'https://i.imgur.com/GRstpeP.jpg'},
         {'nome': 'Raidraptor - Force Strix', 'foto': 'https://i.imgur.com/dJDxG2N.jpg'},
         {'nome': 'Barrier Statue of the Stormwinds', 'foto': 'https://i.imgur.com/DtcMu7r.jpg'},
         {'nome': 'Set Rotation', 'foto': 'https://i.imgur.com/RU6UXFB.jpg'},
         {'nome': 'Black Rose Dragon', 'foto': 'https://i.imgur.com/ybNSBZa.jpg'},
         {'nome': 'Soul Drain', 'foto': 'https://i.imgur.com/YoLye59.jpg'},
         {'nome': 'Terraforming', 'foto': 'https://i.imgur.com/LCPOaLd.jpg'},
         {'nome': 'Ghost Belle & Haunted Mansion', 'foto': 'https://i.imgur.com/jtuqo70.jpg'},
         {'nome': 'Skilled Dark Magician', 'foto': 'https://i.imgur.com/Wo0wnsQ.jpg'},
         {'nome': 'Scapegoat', 'foto': 'https://i.imgur.com/fu2NDAC.jpg'},
         {'nome': 'Lost Wind', 'foto': 'https://i.imgur.com/gR9zeMK.jpg'},
         {'nome': 'Harmonizing Magician', 'foto': 'https://i.imgur.com/rVdEJYZ.jpg'},
         {'nome': 'Golden Bamboo Sword', 'foto': 'https://i.imgur.com/keptx0x.jpg'},
         {'nome': 'Invocation', 'foto': 'https://i.imgur.com/NG8e4A9.jpg'},
         {'nome': 'Legendary Six Samurai - Mizuho', 'foto': 'https://i.imgur.com/0pRRb97.jpg'},
         {'nome': 'Graceful Dice', 'foto': 'https://i.imgur.com/rfTvmxy.jpg'},
         {'nome': 'DNA Surgery', 'foto': 'https://i.imgur.com/h2hpuD3.jpg'},
         {'nome': 'Cyber Twin Dragon', 'foto': 'https://i.imgur.com/dkTaL8S.jpg'},
         {'nome': 'Dark World Dealings', 'foto': 'https://i.imgur.com/wKyPr39.jpg'},
         {'nome': 'Evolzar Laggia', 'foto': 'https://i.imgur.com/N9gb1RW.jpg'},
         {'nome': 'Red-Eyes B. Dragon', 'foto': 'https://i.imgur.com/GxYs33d.jpg'},
         {'nome': 'Great General of the Six Samurai', 'foto': 'https://i.imgur.com/PqWDH0J.jpg'},
         {'nome': 'El Shaddoll Shekhinaga', 'foto': 'https://i.imgur.com/gIuCtVP.jpg'},
         {'nome': 'Saryuja Skull Dread', 'foto': 'https://i.imgur.com/lF59RQ2.jpg'},
         {'nome': 'Legendary Six Samurai - Enishi', 'foto': 'https://i.imgur.com/EOtyScu.jpg'},
         {'nome': 'Psy-Framegear Alpha', 'foto': 'https://i.imgur.com/RJfB7H2.jpg'},
         {'nome': 'Petit Dragon', 'foto': 'https://i.imgur.com/4sJer8P.jpg'},
         {'nome': 'Invoked Mechaba', 'foto': 'https://i.imgur.com/y0xhavA.jpg'},
         {'nome': 'Meda Bat', 'foto': 'https://i.imgur.com/XtAe9LQ.jpg'},
         {'nome': 'Krokodilus', 'foto': 'https://i.imgur.com/7wMiuMi.jpg'},
         {'nome': 'Diciples of the Dracophoenix', 'foto': 'https://i.imgur.com/2ojuWIG.jpg'},
         {'nome': 'Non Aggression Area', 'foto': 'https://i.imgur.com/L7R3z7W.jpg'},
         {'nome': 'Longirsu, the Orcust Orchestrator', 'foto': 'https://i.imgur.com/z0Q6fyE.jpg'},
         {'nome': 'Gold Sarcophagus', 'foto': 'https://i.imgur.com/nUg3g2x.jpg'},
         {'nome': 'Grinder Golem', 'foto': 'https://i.imgur.com/JLZXopJ.jpg'},
         {'nome': 'Satellarknight Deneb', 'foto': 'https://i.imgur.com/408bS9L.jpg'},
         {'nome': 'Scrap Dragon', 'foto': 'https://i.imgur.com/944dj8w.jpg'},
         {'nome': 'Kairyu-Shin', 'foto': 'https://i.imgur.com/y4cpak5.jpg'},
         {'nome': 'Enraged Battle Ox', 'foto': 'https://i.imgur.com/Q0LJbt0.jpg'},
         {'nome': 'Astrograph Sorcerer', 'foto': 'https://i.imgur.com/C1j0IiO.jpg'},
         {'nome': 'Laser Cannon Armor', 'foto': 'https://i.imgur.com/WyRX7tw.jpg'},
         {'nome': 'Underclock Taker', 'foto': 'https://i.imgur.com/oM3QlSY.jpg'},
         {'nome': 'Zoodiac Thoroughblade', 'foto': 'https://i.imgur.com/jMB7TNQ.jpg'},
         {'nome': 'Magic Jammer', 'foto': 'https://i.imgur.com/H9iggh8.jpg'},
         {'nome': 'Dark Bribe', 'foto': 'https://i.imgur.com/RQ1EKgc.jpg'},
         {'nome': 'Raiden, Hand of the Lightsworn', 'foto': 'https://i.imgur.com/W8jalL9.jpg'},
         {'nome': 'Future Fusion', 'foto': 'https://i.imgur.com/pQawfpV.jpg'},
         {'nome': 'Pseudo Space', 'foto': 'https://i.imgur.com/WaipMlc.jpg'},
         {'nome': 'Jinzo', 'foto': 'https://i.imgur.com/qmUFNyf.jpg'},
         {'nome': 'Ib the World Chalice Priestess', 'foto': 'https://i.imgur.com/CjPwkqY.jpg'},
         {'nome': 'Fullmetalfoes Alkahest', 'foto': 'https://i.imgur.com/2V3OWD9.jpg'},
         {'nome': 'Widespread Ruin', 'foto': 'https://i.imgur.com/1PIdejt.jpg'},
         {'nome': 'Widespread Ruin', 'foto': 'https://i.imgur.com/AUH0Ijm.jpg'},
         {'nome': "Shien's Scheme", 'foto': 'https://i.imgur.com/CibjY1m.jpg'},
         {'nome': 'Hieratic Dragon of Tefnuit', 'foto': 'https://i.imgur.com/m08SBjs.jpg'},
         {'nome': 'HalloHallo', 'foto': 'https://i.imgur.com/vqOXNc0.jpg'},
         {'nome': 'Buster Blader', 'foto': 'https://i.imgur.com/oZQYfmr.jpg'},
         {'nome': 'Breakthrough Skill', 'foto': 'https://i.imgur.com/63RJoz1.jpg'},
         {'nome': 'Slate Warrior', 'foto': 'https://i.imgur.com/RFBKlXB.jpg'},
         {'nome': 'Soul Reversal', 'foto': 'https://i.imgur.com/Pruotji.jpg'},
         {'nome': 'Zoodiac Ratpier', 'foto': 'https://i.imgur.com/Ihm5Q4u.jpg'},
         {'nome': 'Beast King Barbaros', 'foto': 'https://i.imgur.com/mWyqJN7.jpg'},
         {'nome': 'Goblin Attack Force', 'foto': 'https://i.imgur.com/xCtripJ.jpg'},
         {'nome': 'Morphing Jar #2', 'foto': 'https://i.imgur.com/jK1iIzU.jpg'},
         {'nome': 'King of the Swamp', 'foto': 'https://i.imgur.com/uvGVdVP.jpg'},
         {'nome': 'Chimeratech Fortress Dragon', 'foto': 'https://i.imgur.com/pSxon3u.jpg'},
         {'nome': 'Super Soldier Soul', 'foto': 'https://i.imgur.com/p5iab3v.jpg'},
         {'nome': 'Darkness Metal, the Dark Steel Dragon', 'foto': 'https://i.imgur.com/cXvU4eL.jpg'},
         {'nome': 'Chain Energy', 'foto': 'https://i.imgur.com/HxTjGh6.jpg'},
         {'nome': 'Graceful Charity', 'foto': 'https://i.imgur.com/dawp5og.jpg'},
         {'nome': 'Rainbow Dark Dragon', 'foto': 'https://i.imgur.com/C8ZnBGi.jpg'},
         {'nome': 'Toon Mask', 'foto': 'https://i.imgur.com/9oOhuQf.jpg'},
         {'nome': 'The White Stone of Legends', 'foto': 'https://i.imgur.com/vMdxFUU.jpg'},
         {'nome': "Summoner's Art", 'foto': 'https://i.imgur.com/77hP7YX.jpg'},
         {'nome': 'Herald of the Arc Light', 'foto': 'https://i.imgur.com/1hwqVox.jpg'},
         {'nome': 'Amorphage Wrath', 'foto': 'https://i.imgur.com/zVtEoVY.jpg'},
         {'nome': 'The Monarchs Stormforth', 'foto': 'https://i.imgur.com/YUlG93t.jpg'},
         {'nome': 'Rocket Arrow Express', 'foto': 'https://i.imgur.com/hzP0Oa3.jpg'},
         {'nome': 'Zoma the Spirit', 'foto': 'https://i.imgur.com/CpJudvM.jpg'},
         {'nome': 'Performapal Whip Snake', 'foto': 'https://i.imgur.com/16QPM1R.jpg'},
         {'nome': 'Secret Skills of the Six Samurai', 'foto': 'https://i.imgur.com/fxbKSVR.jpg'},
         {'nome': 'Swallowtail Butterspy', 'foto': 'https://i.imgur.com/kQgPCje.jpg'},
         {'nome': 'Number 11: Big Eye', 'foto': 'https://i.imgur.com/NkFVtPF.jpg'},
         {'nome': 'Burst Breath', 'foto': 'https://i.imgur.com/JJwViw5.jpg'},
         {'nome': 'Giant Rex', 'foto': 'https://i.imgur.com/yjZhMhM.jpg'},
         {'nome': 'Crimson Blader', 'foto': 'https://i.imgur.com/mtVCRMk.jpg'},
         {'nome': 'Neo-Spacian Grand Mole', 'foto': 'https://i.imgur.com/5V2Evsq.jpg'},
         {'nome': "Elder Entity N'tss", 'foto': 'https://i.imgur.com/3eOU6qH.jpg'},
         {'nome': 'Ultimate Offering', 'foto': 'https://i.imgur.com/7pL0JAB.jpg'},
         {'nome': 'Scarlight Red Dragon Arcfiend', 'foto': 'https://i.imgur.com/2HsEuoM.jpg'},
         {'nome': 'Odd-Eyes Meteorburst Dragon', 'foto': 'https://i.imgur.com/V2JGgOW.jpg'},
         {'nome': 'Jurrac Aeolo', 'foto': 'https://i.imgur.com/YWCTrCK.jpg'},
         {'nome': 'Ghostrick Jiangshi', 'foto': 'https://i.imgur.com/in7EcQ2.jpg'},
         {'nome': 'Frightfur Sabre Tooth', 'foto': 'https://i.imgur.com/RQskeRQ.jpg'},
         {'nome': 'Elemental Hero Captain Gold', 'foto': 'https://i.imgur.com/7xabWd7.jpg'},
         {'nome': 'Fiendish Rhino', 'foto': 'https://i.imgur.com/uEdI6Tu.jpg'},
         {'nome': 'Magical Hats', 'foto': 'https://i.imgur.com/8Riq6ZF.jpg'},
         {'nome': 'Speedroid Terrortop', 'foto': 'https://i.imgur.com/CJ6mts4.jpg'},
         {'nome': 'Yu-Jo Friendship', 'foto': 'https://i.imgur.com/DlvzhNh.jpg'},
         {'nome': 'Stamping Destruction', 'foto': 'https://i.imgur.com/OQfR7gw.jpg'},
         {'nome': 'Foolish Burial', 'foto': 'https://i.imgur.com/9R30Aln.jpg'},
         {'nome': 'Dimensional Fissure', 'foto': 'https://i.imgur.com/Gjl6cYp.jpg'},
         {'nome': 'Dark Effigy', 'foto': 'https://i.imgur.com/VjZDxq9.jpg'},
         {'nome': 'Luminous Spark', 'foto': 'https://i.imgur.com/CznZjNj.jpg'},
         {'nome': 'Needle Worm', 'foto': 'https://i.imgur.com/WFial4r.jpg'},
         {'nome': 'Gem-Knight Lazuli', 'foto': 'https://i.imgur.com/uXiUSNa.jpg'},
         {'nome': "Hiro's Shadow Scout", 'foto': 'https://i.imgur.com/u2ogIIu.jpg'},
         {'nome': 'Ghostrick Specter', 'foto': 'https://i.imgur.com/c7D5xKN.jpg'},
         {'nome': 'Beastly Mirror Ritual', 'foto': 'https://i.imgur.com/Ajv4Iy2.jpg'},
         {'nome': 'Reaper Scythe - Dreadscythe', 'foto': 'https://i.imgur.com/uICFo7l.jpg'},
         {'nome': 'Cipher Wing', 'foto': 'https://i.imgur.com/iJGRCuh.jpg'},
         {'nome': 'Chaos Emperor Dragon - Envoy of the End', 'foto': 'https://i.imgur.com/Tfipd4F.jpg'},
         {'nome': 'Barbar, Malebranche of the Burning Abyss', 'foto': 'https://i.imgur.com/jJQuBQG.jpg'},
         {'nome': 'Toll', 'foto': 'https://i.imgur.com/RBOZ6y6.jpg'},
         {'nome': 'Des Feral Imp', 'foto': 'https://i.imgur.com/TgYFJ6N.jpg'},
         {'nome': 'Skill Drain', 'foto': 'https://i.imgur.com/1Y3wLog.jpg'},
         {'nome': 'Mask of Brutality', 'foto': 'https://i.imgur.com/vzvDQcL.jpg'},
         {'nome': 'Earthquake', 'foto': 'https://i.imgur.com/ySpqtNM.jpg'},
         {'nome': 'Spiral Flame Stike', 'foto': 'https://i.imgur.com/33yspXF.jpg'},
         {'nome': 'Clear Wing Synchro Dragon', 'foto': 'https://i.imgur.com/gxse80l.jpg'},
         {'nome': 'Shine Palace', 'foto': 'https://i.imgur.com/zoVa02x.jpg'},
         {'nome': 'Blade Armor Ninja', 'foto': 'https://i.imgur.com/o9pSNU6.jpg'},
         {'nome': 'Mystic Tomato', 'foto': 'https://i.imgur.com/sS4ZCQ3.jpg'},
         {'nome': 'Grandmaster of the Six Samurai', 'foto': 'https://i.imgur.com/WeohTJC.jpg'},
         {'nome': 'Stim-Pack', 'foto': 'https://i.imgur.com/I3v1WvK.jpg'},
         {'nome': 'Shiranui Shogunsaga', 'foto': 'https://i.imgur.com/TipSoZC.jpg'},
         {'nome': 'Crystron Smiger', 'foto': 'https://i.imgur.com/RUpNKJg.jpg'},
         {'nome': "Nature's Reflection", 'foto': 'https://i.imgur.com/r5Tl9kL.jpg'},
         {'nome': 'Dante, Traveler of the Burning Abyss', 'foto': 'https://i.imgur.com/qPYxkqS.jpg'},
         {'nome': 'Ring of Destruction', 'foto': 'https://i.imgur.com/pEzYwl6.jpg'},
         {'nome': 'Mage Power', 'foto': 'https://i.imgur.com/i1jnLie.jpg'},
         {'nome': 'Monster Reborn', 'foto': 'https://i.imgur.com/1EBu8yq.jpg'},
         {'nome': 'Jar of Greed', 'foto': 'https://i.imgur.com/jtFNWw8.jpg'},
         {'nome': '4-Starred Ladybug', 'foto': 'https://i.imgur.com/gcchiho.jpg'},
         {'nome': 'Number 39: Utopia', 'foto': 'https://i.imgur.com/RyxYxvr.jpg'},
         {'nome': 'Monster Eye', 'foto': 'https://i.imgur.com/Fr8pI9u.jpg'},
         {'nome': 'Domain of the True Monarchs', 'foto': 'https://i.imgur.com/B7Q3Rw2.jpg'},
         {'nome': 'Dian Keto the Cure Master', 'foto': 'https://i.imgur.com/st4zq6j.jpg'},
         {'nome': 'Elemental Hero Clayman', 'foto': 'https://i.imgur.com/aBYyBl5.jpg'},
         {'nome': 'Gorgonic Guardian', 'foto': 'https://i.imgur.com/auG8WXb.jpg'},
         {'nome': 'Form Change', 'foto': 'https://i.imgur.com/d3ltBgh.jpg'},
         {'nome': 'Slushy', 'foto': 'https://i.imgur.com/iTYWTXi.jpg'},
         {'nome': 'Solemn Warning', 'foto': 'https://i.imgur.com/fsLICKU.jpg'},
         {'nome': 'Scarm, Malebranche of the Burning Abyss', 'foto': 'https://i.imgur.com/Ze4W7Ht.jpg'},
         {'nome': 'Lunalight White Rabbit', 'foto': 'https://i.imgur.com/KLYieyn.jpg'},
         {'nome': 'World Chalice Guardragon', 'foto': 'https://i.imgur.com/aoFwPv1.jpg'},
         {'nome': 'Beelzeus of the Ultimate Dark Dragon', 'foto': 'https://i.imgur.com/KM3NlTW.jpg'},
         {'nome': 'The Immortal of Thunder', 'foto': 'https://i.imgur.com/227hMGC.jpg'},
         {'nome': 'Needlebug Nest', 'foto': 'https://i.imgur.com/9G7MYDL.jpg'},
         {'nome': 'Gouki Octostretch', 'foto': 'https://i.imgur.com/TEUsQAi.jpg'},
         {'nome': 'Brain Research Lab', 'foto': 'https://i.imgur.com/qMAWI8k.jpg'},
         {'nome': 'Zoodiac Broadbull', 'foto': 'https://i.imgur.com/mkV8Dpc.jpg'},
         {'nome': 'Card Trooper', 'foto': 'https://i.imgur.com/rlWRfCE.jpg'},
         {'nome': 'Artifact Moralltach', 'foto': 'https://i.imgur.com/xputBxR.jpg'},
         {'nome': 'Zefra Metaltron', 'foto': 'https://i.imgur.com/7X1Tf2i.jpg'},
         {'nome': 'Berserk Dragon', 'foto': 'https://i.imgur.com/lpf6Nrf.jpg'},
         {'nome': 'Rescue Rabbit', 'foto': 'https://i.imgur.com/OCrY8y1.jpg'},
         {'nome': 'Blackwing - Kalut the Moon Shadow', 'foto': 'https://i.imgur.com/Bdtvv2W.jpg'},
         {'nome': 'Frightfur Bear', 'foto': 'https://i.imgur.com/yxp3bxb.jpg'},
         {'nome': 'Dark Room of Nightmare', 'foto': 'https://i.imgur.com/narKolH.jpg'},
         {'nome': 'Beelze the Diabolic Dragons', 'foto': 'https://i.imgur.com/ZsVEK1E.jpg'}]

PROVINCES = [542406551923720202,
             542406630218661929,
             542406759017611275,
             542406909278420992,
             542406979151462430,
             542407056339238922,
             542407122558779404,
             542407283750076514,
             542407345750278164,
             542407416768233530]

ERRORS = ['The check functions for command staff ban failed.',
          'The check functions for command staff kick failed.',
          'The check functions for command staff language failed.',
          'The check functions for command staff limpar failed.',
          'Command raised an exception: IndexError: list index out of range',
          'Command raised an exception: TimeoutError: ',
          'The check functions for command config guild failed.',
          'The check functions for command config report failed.',
          'The check functions for command staff slowmode failed.']

enforcado = ['''
```
X==:==
X  :   
X   
X 
X 
X
===========
```''', '''
```
X==:==
X  :   
X  O   
X  
X  
X
===========
```''', '''
```
X==:==
X  :   
X  O   
X  |
X  
X
===========
```''', '''
```
X==:==
X  :   
X  O   
X \|
X 
X
===========
```''', '''
```
X==:==
X  :   
X  O   
X \|/ 
X  
X
===========
```''', '''
```
X==:==
X  :   
X  O   
X \|/ 
X /  
X
===========
```
''', '''
```
X==:==
X  :   
X  O   
X \|/ 
X / \ 
X
===========
```''']
forca = {'Pokemon': 'Mewtwo',
         'Programador': 'Denky',
         'Sayajin': 'Vegeta',
         'Dattebayo': 'Naruto',
         'Evento Natural': 'Ciclone',
         'Emprego': 'Você não tem',
         'Patchouli': 'Bot',
         'Filme': 'Matrix',
         'Anime': 'Bleach',
         'o especialista em doenças dos ouvidos e garganta': 'Otorrinolaringologista',
         'Aquele que tem constancias nas suas ações': 'Perseverança',
         'Battle Royale': 'free fire',
         'FPS': 'counter strike',
         'RPG': 'final fantasy',
         'Animal de Estimação': 'tamagotchi',
         'Console': 'Atari',
         'Computador': 'placa de video',
         'Bruxa': 'Sabrina',
         'Deus Antigo: Lovecraft': 'cthulhu',
         'Mensageiro': 'MSN',
         'Longo': 'one piece',
         'Acervo dos Animes': 'Crunchroll',
         'Uma trap dos Animes': 'Himegoto',
         'haunted astolfo bean plushie that sucks your dick and calls you gay': 'Pelucia do Mal',
         'Vampiro': 'Alucard',
         'Rei Arthur': 'excalibur',
         'Monstros em Cartas': 'sakura card captors',
         'haunted plushie that drinks all your pepsi and calls you bitch': 'Pelucia Assombrada',
         'Filosofo': 'python',
         'Vicio': 'alcoolismo',
         'Bizarro': 'jojo kimyou na bouken',
         'Musica de Qualidade': 'cu de cachorro',
         'Ravioli Ravioli': 'dont lewd the dragon loli',
         'Dragão de Raio': 'kanna Kamui',
         'Cry Baby': 'melanie martinez',
         'Borracha': 'flexibilidade',
         'michael jackson': 'billie jean',
         'Gas': 'lacrimogenio',
         'Dungeon': 'catatumba',
         'FTK': 'First Turn Kill',
         'Seu Madruga': 'ambulante',
         'fruta': 'mamão papaia',
         'pato': 'Patolino',
         'Rabo das Fada': 'fairy tail',
         'Disney': 'mickey mouse',
         'Qualidade': 'ashley',
         'Viagem no tempo': 'steins gate',
         'J.A.R.V.I.S.': 'inteligencia artificial',
         'Cozinha': 'geladeira',
         'Furduncio': 'treta news',
         'Terror': 'globglogabgalab',
         'Scar': 'Vida Longa ao Rei',
         'Você Tambem Não Tem': 'namorada',
         'Muro': 'donald trump',
         'Periférico de Saida': 'Impressora',
         'caçador espacial': 'predador',
         'Menino Ixpertinho': 'felipe neto',
         'Rainha dos Baixinhos': 'xuxa meneguel',
         'Deus Fraco': 'loki odinson',
         'Debonho': 'daniel com f',
         'anom de la bandana': 'nando moura',
         'mamifero blindado': 'baleia caveirão',
         'China': 'pastel de flango',
         'Racismo': 'ku klux klan',
         'Atirador': 'revolver ocelot',
         'Playstation': 'bom dia & cia',
         'Team 9': 'cirno',
         'Santo Boxe': 'jesus stole my bike',
         'Desceu Pela Privada': 'voce mesmo',
         'Eh Ue': 'Galo Cego',
         'veneno': 'Dolly',
         'Mister Anderson': "he's beginning to believe",
         'Use a varinha': 'dumbledore',
         'Harry Porra': 'a vara quer raba',
         'anti-otacu supremo': 'overlord',
         'Maior erro da humanidade': 'seu nascimento',
         'Loiro Gelado': 'hyoga de cisne',
         'Hentai': 'bowsette',
         'onde está o botas?': 'dora, a aventureira',
         'Tudo': 'Regra 34',
         'Mother Russian': 'vladimir putin',
         'Russian Warrior': 'katyusha',
         'Wodka': 'Adoro',
         'Invasor': 'rezende evil',
         'eh ta bom': 'silvio santos',
         'Waifu Simulator': 'overwatch',
         'Drift': 'Cadeira de Rodas',
         'Comeram': 'sua mãe',
         'Entra no robo': 'Power Rangers',
         'Deus do Novo Mundo': 'light yagami',
         'Digimon': 'digievolução',
         'Kami': 'kaname madoka',
         'Debiru': 'akemi homura',
         'Acre': 'Dinossauro',
         'Todo mundo chora por ela ou rir de quem tem': 'Gaia',
         'Will Smith': 'Um maluco no pedaço',
         'Palhaço': 'coringa',
         'xbox': 'hallo',
         'Senpai': 'Terry Yutem',
         'Ele é a justiça': 'Lawliet',
         'se me der a mão eu te levarei por um caminho cheio de:': 'sombras e de luz',
         'EPIC!': 'gaveta filmes',
         'Lambda Lambda Lambda': 'jovem nerd',
         'Se o Aranha fosse brasileiro': 'o miranha'}

goodbye = ['tchau', 'xau', 'adeus', 'ate mais', 'ate a proxima', 'fim', 'finalizar', 'desliga', 'logoff', 'bye',
           'goodbye']

negate = ['desculpe eu nao conseguir entender!', 'sinto muito, mas não tenho essa informação!',
          'isso nao consta no meu banco de dados.', 'não sei, ainda preciso aprender sobre isso!']

pokemon = [{'nome': 'Caterpie', 'foto': 'https://i.imgur.com/Y5wlakH.jpg'},
           {'nome': 'Wigglytuff', 'foto': 'https://i.imgur.com/49SWnIR.jpg'},
           {'nome': 'Jigglypuff', 'foto': 'https://i.imgur.com/gXvpL3V.jpg'},
           {'nome': 'Ninetails', 'foto': 'https://i.imgur.com/kQ6h2eX.jpg'},
           {'nome': 'Vulpix', 'foto': 'https://i.imgur.com/JUKzHo9.jpg'},
           {'nome': 'Bulbasaur', 'foto': 'https://i.imgur.com/NGVhnfs.jpg'},
           {'nome': 'Ivysaur', 'foto': 'https://i.imgur.com/NURwq3O.jpg'},
           {'nome': 'Venosaur', 'foto': 'https://i.imgur.com/7dgaQr0.jpg'},
           {'nome': 'Charmander', 'foto': 'https://i.imgur.com/ctRzE7T.jpg'},
           {'nome': 'Charmeleon', 'foto': 'https://i.imgur.com/nX0mmO1.jpg'},
           {'nome': 'Charizard', 'foto': 'https://i.imgur.com/gDGki1C.jpg'},
           {'nome': 'Squirtle', 'foto': 'https://i.imgur.com/cOZecwm.jpg'},
           {'nome': 'Wartortle', 'foto': 'https://i.imgur.com/a5Hpzat.jpg'},
           {'nome': 'Metapod', 'foto': 'https://i.imgur.com/6kHfUGE.jpg'},
           {'nome': 'Butterfree', 'foto': 'https://i.imgur.com/2kMbqoF.jpg'},
           {'nome': 'Weedle', 'foto': 'https://i.imgur.com/8lnEZDO.jpg'},
           {'nome': 'Kakuna', 'foto': 'https://i.imgur.com/sdIM9kz.jpg'},
           {'nome': 'Beedrill', 'foto': 'https://i.imgur.com/OySQPak.jpg'},
           {'nome': 'Pidgey', 'foto': 'https://i.imgur.com/kGeZWW7.jpg'},
           {'nome': 'Blastoise', 'foto': 'https://i.imgur.com/Hb9JliS.jpg'},
           {'nome': 'Clefable', 'foto': 'https://i.imgur.com/1zlpVWk.jpg'},
           {'nome': 'Clefairy', 'foto': 'https://i.imgur.com/RWTMkux.jpg'},
           {'nome': 'Ponyta', 'foto': 'https://i.imgur.com/FIQgR5f.jpg'},
           {'nome': 'Nidoking', 'foto': 'https://i.imgur.com/vc4GByy.jpg'},
           {'nome': 'Nidorino', 'foto': 'https://i.imgur.com/1S2AZXy.jpg'},
           {'nome': 'Nidoran', 'foto': 'https://i.imgur.com/9C7b7f5.jpg'},
           {'nome': 'Nidoqueen', 'foto': 'https://i.imgur.com/24H1Kkx.jpg'},
           {'nome': 'Nidorina', 'foto': 'https://i.imgur.com/vLNPfJ6.jpg'},
           {'nome': 'Nidoran', 'foto': 'https://i.imgur.com/Nbwi0cc.jpg'},
           {'nome': 'Sandslash', 'foto': 'https://i.imgur.com/s6bIGCE.jpg'},
           {'nome': 'Sandshrew', 'foto': 'https://i.imgur.com/wMz9Lem.jpg'},
           {'nome': 'Raichu', 'foto': 'https://i.imgur.com/RSk1rzI.jpg'},
           {'nome': 'Pikachu', 'foto': 'https://i.imgur.com/TjFc9tR.jpg'},
           {'nome': 'Arbok', 'foto': 'https://i.imgur.com/SVm1f5b.jpg'},
           {'nome': 'Ekans', 'foto': 'https://i.imgur.com/vXx2RBE.jpg'},
           {'nome': 'Spearow', 'foto': 'https://i.imgur.com/tkj8fjx.jpg'},
           {'nome': 'Fearow', 'foto': 'https://i.imgur.com/xLLmNZQ.jpg'},
           {'nome': 'Raticate', 'foto': 'https://i.imgur.com/zXaV5At.jpg'},
           {'nome': 'Ratata', 'foto': 'https://i.imgur.com/yqcnBFC.jpg'},
           {'nome': 'Pidgeot', 'foto': 'https://i.imgur.com/fMSyj5F.jpg'},
           {'nome': 'Pidgeotto', 'foto': 'https://i.imgur.com/OUhGxy6.jpg'},
           {'nome': 'Growlithe', 'foto': 'https://i.imgur.com/ggWTmxa.jpg'},
           {'nome': 'Kadabra', 'foto': 'https://i.imgur.com/4tJqmQN.jpg'},
           {'nome': 'Poliwrath', 'foto': 'https://i.imgur.com/eDfqWIl.jpg'},
           {'nome': 'Poliwhirl', 'foto': 'https://i.imgur.com/1D6AxQp.jpg'},
           {'nome': 'Poliwag', 'foto': 'https://i.imgur.com/I4oK8X8.jpg'},
           {'nome': 'Abra', 'foto': 'https://i.imgur.com/NQrq0us.jpg'},
           {'nome': 'Primape', 'foto': 'https://i.imgur.com/fkCRL81.jpg'},
           {'nome': 'Dugtrio', 'foto': 'https://i.imgur.com/Kr4Wsu1.jpg'},
           {'nome': 'Venomoth', 'foto': 'https://i.imgur.com/oJbaeww.jpg'},
           {'nome': 'Arcanine', 'foto': 'https://i.imgur.com/5wIckPG.jpg'},
           {'nome': 'Meowth', 'foto': 'https://i.imgur.com/4a9N9Uh.jpg'},
           {'nome': 'Golduck', 'foto': 'https://i.imgur.com/jo5OQyQ.jpg'},
           {'nome': 'Persian', 'foto': 'https://i.imgur.com/nQcIxLw.jpg'},
           {'nome': 'Psyduck', 'foto': 'https://i.imgur.com/5IZEBVi.jpg'},
           {'nome': 'Venonat', 'foto': 'https://i.imgur.com/ImyKYTf.jpg'},
           {'nome': 'Parasect', 'foto': 'https://i.imgur.com/MffTMol.jpg'},
           {'nome': 'Paras', 'foto': 'https://i.imgur.com/jLv7sYe.jpg'},
           {'nome': 'Diglett', 'foto': 'https://i.imgur.com/YemH5k4.jpg'},
           {'nome': 'Mankey', 'foto': 'https://i.imgur.com/h3GIKs9.jpg'},
           {'nome': 'Vileplume', 'foto': 'https://i.imgur.com/edkk2bA.jpg'},
           {'nome': 'Gloom', 'foto': 'https://i.imgur.com/VnowEq7.jpg'},
           {'nome': 'Oddish', 'foto': 'https://i.imgur.com/aHXcGNc.jpg'},
           {'nome': 'Golbat', 'foto': 'https://i.imgur.com/SPOuyYh.jpg'},
           {'nome': 'Zubat', 'foto': 'https://i.imgur.com/A5LtLCl.jpg'},
           {'nome': 'Drowzee', 'foto': 'https://i.imgur.com/P9IwNKm.jpg'},
           {'nome': 'Onix', 'foto': 'https://i.imgur.com/yjI17FU.jpg'},
           {'nome': 'Dodrio', 'foto': 'https://i.imgur.com/HwOsGL3.jpg'},
           {'nome': 'Gengar', 'foto': 'https://i.imgur.com/rdhSXQM.jpg'},
           {'nome': 'Farfetch', 'foto': 'https://i.imgur.com/85bN4uT.jpg'},
           {'nome': 'Haunter', 'foto': 'https://i.imgur.com/2dEJ92E.jpg'},
           {'nome': 'Dewgong', 'foto': 'https://i.imgur.com/R30JAQ5.jpg'},
           {'nome': 'Gastly', 'foto': 'https://i.imgur.com/OnScWET.jpg'},
           {'nome': 'Cloyster', 'foto': 'https://i.imgur.com/M5W6XHw.jpg'},
           {'nome': 'Shelter', 'foto': 'https://i.imgur.com/WgPn0cf.jpg'},
           {'nome': 'Muk', 'foto': 'https://i.imgur.com/MphoUxq.jpg'},
           {'nome': 'Seel', 'foto': 'https://i.imgur.com/EUKKMsF.jpg'},
           {'nome': 'Grimmer', 'foto': 'https://i.imgur.com/otG8Sip.jpg'},
           {'nome': 'Doduo', 'foto': 'https://i.imgur.com/SCkltCP.jpg'},
           {'nome': 'Magneton', 'foto': 'https://i.imgur.com/T0cEarH.jpg'},
           {'nome': 'Magnemite', 'foto': 'https://i.imgur.com/n0fdkxz.jpg'},
           {'nome': 'Slowbro', 'foto': 'https://i.imgur.com/6zka3gM.jpg'},
           {'nome': 'Slowpoke', 'foto': 'https://i.imgur.com/DkKKUvx.jpg'},
           {'nome': 'Rapidash', 'foto': 'https://i.imgur.com/DcoFaa3.jpg'},
           {'nome': 'Weepinbel', 'foto': 'https://i.imgur.com/Xd8uzdw.jpg'},
           {'nome': 'Graveler', 'foto': 'https://i.imgur.com/L4esA0i.jpg'},
           {'nome': 'Geodude', 'foto': 'https://i.imgur.com/jD2PYqQ.jpg'},
           {'nome': 'Golem', 'foto': 'https://i.imgur.com/PeIIzG3.jpg'},
           {'nome': 'Tentacruel', 'foto': 'https://i.imgur.com/hAuD5MQ.jpg'},
           {'nome': 'Victreebel', 'foto': 'https://i.imgur.com/wy5I4kp.jpg'},
           {'nome': 'Tentacool', 'foto': 'https://i.imgur.com/JsQ8QoK.jpg'},
           {'nome': 'Bellsprout', 'foto': 'https://i.imgur.com/X04ibrx.jpg'},
           {'nome': 'Machamp', 'foto': 'https://i.imgur.com/i5yYP5R.jpg'},
           {'nome': 'Machoke', 'foto': 'https://i.imgur.com/CZXDDSU.jpg'},
           {'nome': 'Machop', 'foto': 'https://i.imgur.com/sJMJDHJ.jpg'},
           {'nome': 'Alakazam', 'foto': 'https://i.imgur.com/4Za9eKs.jpg'},
           {'nome': 'Sciter', 'foto': 'https://i.imgur.com/HE4sns9.jpg'},
           {'nome': 'Mr. Mime', 'foto': 'https://i.imgur.com/MIQ9ZIb.jpg'},
           {'nome': 'Starmie', 'foto': 'https://i.imgur.com/pJorPfj.jpg'},
           {'nome': 'Electabuzz', 'foto': 'https://i.imgur.com/CeJiJrJ.jpg'},
           {'nome': 'Jinx', 'foto': 'https://i.imgur.com/F60fPNP.jpg'},
           {'nome': 'Magmar', 'foto': 'https://i.imgur.com/nJHnKxD.jpg'},
           {'nome': 'Pinsir', 'foto': 'https://i.imgur.com/DzupTdN.jpg'},
           {'nome': 'Tauros', 'foto': 'https://i.imgur.com/NriC5qR.jpg'},
           {'nome': 'Staryu', 'foto': 'https://i.imgur.com/NqyPvgp.jpg'},
           {'nome': 'Seaking', 'foto': 'https://i.imgur.com/vkLFeaS.jpg'},
           {'nome': 'Goldeen', 'foto': 'https://i.imgur.com/y6QO8yM.jpg'},
           {'nome': 'Seadra', 'foto': 'https://i.imgur.com/DteBgN4.jpg'},
           {'nome': 'Lickitung', 'foto': 'https://i.imgur.com/O8yZm0K.jpg'},
           {'nome': 'Horsea', 'foto': 'https://i.imgur.com/7kk9FH2.jpg'},
           {'nome': 'Weezing', 'foto': 'https://i.imgur.com/wO7BZBC.jpg'},
           {'nome': 'Chansey', 'foto': 'https://i.imgur.com/AH1I1Iq.jpg'},
           {'nome': 'Tangela', 'foto': 'https://i.imgur.com/rifVOz3.jpg'},
           {'nome': 'Hitmonlee', 'foto': 'https://i.imgur.com/iyG4ALK.jpg'},
           {'nome': 'Kengaskan', 'foto': 'https://i.imgur.com/o7drSws.jpg'},
           {'nome': 'Hitmonchan', 'foto': 'https://i.imgur.com/QC0nzRA.jpg'},
           {'nome': 'koffing', 'foto': 'https://i.imgur.com/dcPFJXv.jpg'},
           {'nome': 'Marowak', 'foto': 'https://i.imgur.com/Ll7lmyT.jpg'},
           {'nome': 'Rhyhorn', 'foto': 'https://i.imgur.com/oUY3E61.jpg'},
           {'nome': 'Rhydon', 'foto': 'https://i.imgur.com/ZLoIKZ9.jpg'},
           {'nome': 'Cubone', 'foto': 'https://i.imgur.com/ObFQENw.jpg'},
           {'nome': 'Exeggutor', 'foto': 'https://i.imgur.com/rMowfs9.jpg'},
           {'nome': 'Exeggcute', 'foto': 'https://i.imgur.com/SLjjpwL.jpg'},
           {'nome': 'Electrode', 'foto': 'https://i.imgur.com/gjL51Yj.jpg'},
           {'nome': 'Voltorb', 'foto': 'https://i.imgur.com/KX4ZTOH.jpg'},
           {'nome': 'Krabby', 'foto': 'https://i.imgur.com/pMKJpKC.jpg'},
           {'nome': 'Kingler', 'foto': 'https://i.imgur.com/F5w32w1.jpg'},
           {'nome': 'Hypno', 'foto': 'https://i.imgur.com/UGiMUu7.jpg'},
           {'nome': 'Mew', 'foto': 'https://i.imgur.com/trcEpKE.jpg'},
           {'nome': 'Kabutops', 'foto': 'https://i.imgur.com/c7L3g4d.jpg'},
           {'nome': 'Mewtwo', 'foto': 'https://i.imgur.com/4fkWYuN.jpg'},
           {'nome': 'Dragonite', 'foto': 'https://i.imgur.com/9yBVqMO.jpg'},
           {'nome': 'Dratini', 'foto': 'https://i.imgur.com/j0Sw1XB.jpg'},
           {'nome': 'Dragonair', 'foto': 'https://i.imgur.com/LRz0uDE.jpg'},
           {'nome': 'Moltres', 'foto': 'https://i.imgur.com/Xyq7JDN.jpg'},
           {'nome': 'Omastar', 'foto': 'https://i.imgur.com/Nc5DMVE.jpg'},
           {'nome': 'Omanite', 'foto': 'https://i.imgur.com/Nx1S6GW.jpg'},
           {'nome': 'Porygon', 'foto': 'https://i.imgur.com/7e5rJjM.jpg'},
           {'nome': 'Zapdos', 'foto': 'https://i.imgur.com/aHyKnco.jpg'},
           {'nome': 'Kabuto', 'foto': 'https://i.imgur.com/l4PMipK.jpg'},
           {'nome': 'Aerodactyl', 'foto': 'https://i.imgur.com/VjgfojP.jpg'},
           {'nome': 'Snorlax', 'foto': 'https://i.imgur.com/D3wLde0.jpg'},
           {'nome': 'Articuno', 'foto': 'https://i.imgur.com/zqN3Gpx.jpg'},
           {'nome': 'Flareon', 'foto': 'https://i.imgur.com/IUl1uLF.jpg'},
           {'nome': 'Jolteon', 'foto': 'https://i.imgur.com/RaLyTIL.jpg'},
           {'nome': 'Vaporeon', 'foto': 'https://i.imgur.com/jVkczVm.jpg'},
           {'nome': 'Eevee', 'foto': 'https://i.imgur.com/HDUqpUl.jpg'},
           {'nome': 'Margikarp', 'foto': 'https://i.imgur.com/FjaPIe8.jpg'},
           {'nome': 'Lapras', 'foto': 'https://i.imgur.com/KvxTc0l.jpg'},
           {'nome': 'Gyarados', 'foto': 'https://i.imgur.com/E8fi3f6.jpg'},
           {'nome': 'Ditto', 'foto': 'https://i.imgur.com/WbBS0ve.jpg'}]
